<div class="d-flex justify-content-between align-items-start gap-3 mb-4 flex-wrap"><div><h1 class="h3 mb-1">Abrechnung</h1><p class="text-body-secondary mb-0">Abrechenbare, noch nicht an SevDesk exportierte Prüfungen inklusive Regiezeit.</p></div><span class="badge text-bg-<?= $configured ? 'success' : 'warning' ?>"><?= $configured ? 'SevDesk konfiguriert' : 'SevDesk noch nicht konfiguriert' ?></span></div>
<?php if (!empty($message)): ?><div class="alert alert-info"><?= htmlspecialchars((string) $message) ?></div><?php endif; ?>
<form method="post" action="<?= htmlspecialchars(url_for('admin/abrechnung/export'), ENT_QUOTES) ?>">
<div class="card"><div class="card-body"><div class="d-flex gap-2 mb-3 flex-wrap"><button class="btn btn-primary" name="action" value="csv">CSV für Rechnung exportieren</button><button class="btn btn-outline-primary" name="action" value="sevdesk"<?= $configured ? '' : ' disabled' ?>>Als SevDesk-Entwurf senden</button><button class="btn btn-outline-secondary" name="action" value="mark">Als exportiert markieren</button></div>
<?php if (!$configured): ?><div class="alert alert-warning small">Hinterlege im Mandanten unter „SevDesk“ API-URL und API-Token. Die Prüfungen bleiben bis dahin exportierbar als CSV.</div><?php endif; ?>
<div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th><input type="checkbox" id="billing-all" aria-label="Alle auswählen"></th><th>Prüfung</th><th>Datum</th><th>Kunde</th><th>Gerät</th><th>Raum</th><th>Ergebnis</th><th>Regie</th><th>SevDesk-Kunde</th></tr></thead><tbody>
<?php foreach ($rows as $row): ?><tr><td><input class="billing-check" type="checkbox" name="inspection_ids[]" value="<?= (int) $row['id'] ?>"></td><td><?= htmlspecialchars((string) $row['external_number']) ?></td><td><?= htmlspecialchars((string) $row['test_date']) ?></td><td><?= htmlspecialchars((string) $row['customer_name']) ?></td><td><?= htmlspecialchars((string) $row['device_number']) ?> · <?= htmlspecialchars((string) $row['device_name']) ?></td><td><?= htmlspecialchars(trim(implode(' · ', array_filter([$row['site_name'], $row['building_name'], $row['floor_name'], $row['room_number']]))) ?: '—') ?></td><td><span class="badge text-bg-<?= $row['result_status'] === 'bestanden' ? 'success' : 'danger' ?>"><?= htmlspecialchars((string) $row['result_status']) ?></span></td><td><?= (int) $row['regie_minutes'] ?> Min.<?php if ($row['regie_reason'] !== ''): ?><div class="small text-body-secondary"><?= htmlspecialchars((string) $row['regie_reason']) ?></div><?php endif; ?></td><td><?= ($row['sevdesk_customer_number'] ?? '') !== '' ? htmlspecialchars((string) $row['sevdesk_customer_number']) : (($row['sevdesk_customer_id'] ?? '') !== '' ? htmlspecialchars((string) $row['sevdesk_customer_id']) : '<span class="text-danger">fehlt</span>') ?></td></tr><?php endforeach; ?>
<?php if ($rows === []): ?><tr><td colspan="9" class="text-body-secondary">Keine offenen abrechenbaren Prüfungen.</td></tr><?php endif; ?></tbody></table></div></div></div></form>
<script>document.getElementById('billing-all')?.addEventListener('change',e=>document.querySelectorAll('.billing-check').forEach(c=>c.checked=e.target.checked));</script>
