<div class="d-flex justify-content-between align-items-start gap-3 mb-4 flex-wrap">
  <div><h1 class="h3 mb-1">Rechnung #<?= (int) $invoice->id ?></h1><p class="text-body-secondary mb-0">Abrechnungsnachweis und verknüpfte Prüfungen</p></div>
  <a class="btn btn-outline-secondary" href="<?= htmlspecialchars(url_for('admin/abrechnung'), ENT_QUOTES) ?>">Zur Abrechnung</a>
</div>
<?php
$reconciliation = $reconciliation ?? [];
$formatQuantity = static function (mixed $value): string {
  $number = (float) $value;
  return fmod($number, 1.0) === 0.0 ? (string) (int) $number : rtrim(rtrim(number_format($number, 3, ',', '.'), '0'), ',');
};
$sevDeskPositions = array_map(static function (array $position) use ($formatQuantity): string {
  $suffix = BillingController::displaySevDeskUnit((string) ($position['unit'] ?? ''));
  $label = trim((string) ($position['name'] ?? ''));
  $line = trim($formatQuantity($position['quantity'] ?? 0) . ' ' . $suffix . ' ' . $label);
  if ((string) ($position['suggested_kind'] ?? '') === 'regie' && (int) ($position['regie_minutes'] ?? 0) > 0) {
    $line .= ' (' . (int) $position['regie_minutes'] . ' Min. Regie)';
  }
  return $line;
}, $reconciliation['positions'] ?? []);
?>
<dl class="row">
  <dt class="col-sm-3">Rechnungsnummer</dt><dd class="col-sm-9"><?= htmlspecialchars((string) ($invoice->invoice_number ?: '—')) ?></dd>
  <dt class="col-sm-3">SevDesk-ID</dt><dd class="col-sm-9"><?= htmlspecialchars((string) ($invoice->sevdesk_invoice_id ?: '—')) ?><?php if (trim((string) ($invoice->sevdesk_url ?? '')) !== ''): ?> · <a href="<?= htmlspecialchars((string) $invoice->sevdesk_url, ENT_QUOTES) ?>" target="_blank" rel="noopener">In SevDesk öffnen</a><?php endif; ?></dd>
  <dt class="col-sm-3">SevDesk-Rechnungsnummer</dt><dd class="col-sm-9"><?= htmlspecialchars((string) ($invoice->sevdesk_invoice_number ?: '—')) ?></dd>
  <dt class="col-sm-3">Datum</dt><dd class="col-sm-9"><?= htmlspecialchars((string) ($invoice->invoice_date ?: '—')) ?></dd>
  <dt class="col-sm-3">SevDesk-Positionen</dt><dd class="col-sm-9"><?= $sevDeskPositions === [] ? '—' : htmlspecialchars(implode(' · ', $sevDeskPositions)) ?></dd>
  <dt class="col-sm-3">Leistungszeitraum</dt><dd class="col-sm-9"><?php $from = trim((string) ($invoice->performance_date_from ?? '')); $until = trim((string) ($invoice->performance_date_until ?? '')); ?><?= htmlspecialchars($from === '' ? '—' : ($from === $until || $until === '' ? $from : $from . ' bis ' . $until)) ?></dd>
  <?php if (trim((string) ($invoice->recipient_address ?? '')) !== ''): ?><dt class="col-sm-3">Rechnungsempfänger</dt><dd class="col-sm-9"><?= nl2br(htmlspecialchars((string) $invoice->recipient_address)) ?></dd><?php endif; ?>
  <dt class="col-sm-3">Status</dt><dd class="col-sm-9"><span class="badge text-bg-secondary"><?= htmlspecialchars((string) $invoice->status) ?></span></dd>
</dl>
<section class="card mb-4" id="billing-reconciliation">
  <div class="card-header fw-semibold"><i class="fa-solid fa-scale-balanced me-2" aria-hidden="true"></i>Rechnungsabgleich</div>
  <div class="card-body">
    <div class="row g-3">
      <div class="col-md-3"><strong>Geräte laut Rechnung</strong><div><?= htmlspecialchars((string) ($reconciliation['deviceTarget'] ?? 0)) ?></div></div>
      <div class="col-md-3"><strong>Geräte zugeordnet</strong><div><?= htmlspecialchars((string) ($reconciliation['deviceActual'] ?? 0)) ?></div></div>
      <div class="col-md-3"><strong>Regie laut Rechnung</strong><div><?= (int) ($reconciliation['regieTarget'] ?? 0) ?> Minuten</div></div>
      <div class="col-md-3"><strong>Regie zugeordnet</strong><div><?= (int) ($reconciliation['regieActual'] ?? 0) ?> Minuten</div></div>
    </div>
    <div class="mt-3"><span class="badge text-bg-<?= (($reconciliation['result'] ?? '') === 'vollständig passend') ? 'success' : 'warning text-dark' ?>"><?= htmlspecialchars((string) ($reconciliation['result'] ?? 'Zuordnung unvollständig')) ?></span><span class="small text-body-secondary ms-2">Doppelte Prüfnummern: <?= (int) ($reconciliation['duplicates'] ?? 0) ?> · Nicht klassifizierte Rechnungspositionen: <?= (int) ($reconciliation['unclassified'] ?? 0) ?></span></div>
    <?php if (($reconciliation['positions'] ?? []) !== []): ?>
      <?php if (current_user_is_superadmin()): ?><form method="post" action="<?= htmlspecialchars(url_for('admin/abrechnung/rechnung/' . (int) $invoice->id . '/positionen-klassifizieren'), ENT_QUOTES) ?>" hx-post="<?= htmlspecialchars(url_for('admin/abrechnung/rechnung/' . (int) $invoice->id . '/positionen-klassifizieren'), ENT_QUOTES) ?>" hx-target="#billing-reconciliation" hx-select="#billing-reconciliation" hx-swap="outerHTML"><?php endif; ?>
      <div class="table-responsive mt-3"><table class="table table-sm mb-0"><thead><tr><th>Position</th><th>Bezeichnung</th><th>Menge</th><th>Einheit</th><th>Zuordnung</th></tr></thead><tbody>
      <?php foreach ($reconciliation['positions'] as $position): $storedKind = (string) $position['kind']; $suggestedKind = (string) $position['suggested_kind']; $selectedKind = in_array($storedKind, ['device', 'regie', 'other'], true) ? $storedKind : (in_array($suggestedKind, ['device', 'regie', 'other'], true) ? $suggestedKind : ''); ?>
        <tr><td><?= htmlspecialchars((string) $position['position_number']) ?></td><td><?= htmlspecialchars((string) $position['name']) ?></td><td><?= htmlspecialchars((string) $position['quantity']) ?></td><td><?= htmlspecialchars(BillingController::displaySevDeskUnit((string) $position['unit'])) ?></td><td>
          <?php if (current_user_is_superadmin()): ?>
            <div class="d-flex flex-wrap gap-1 align-items-center">
              <select class="form-select form-select-sm" name="positions[<?= (int) $position['id'] ?>][kind]" aria-label="Positionsart">
                <option value="" disabled<?= $selectedKind === '' ? ' selected' : '' ?>>Bitte festlegen</option>
                <?php foreach (['device' => 'Geräte', 'regie' => 'Regie', 'other' => 'Sonstige'] as $value => $label): ?><option value="<?= $value ?>"<?= $selectedKind === $value ? ' selected' : '' ?>><?= $label ?></option><?php endforeach; ?>
              </select>
              <input class="form-control form-control-sm" name="positions[<?= (int) $position['id'] ?>][regie_minutes]" type="number" min="0" value="<?= (int) $position['regie_minutes'] ?>" aria-label="Regiezeit in Minuten" title="Nur bei Regie: Minuten">
              <?php if ($storedKind === 'unclassified' && $selectedKind !== ''): ?><span class="small text-body-secondary"><i class="fa-solid fa-wand-magic-sparkles me-1" aria-hidden="true"></i>Vorschlag – bitte prüfen</span><?php endif; ?>
            </div>
          <?php else: ?><span class="badge text-bg-secondary"><?= htmlspecialchars($storedKind === 'unclassified' ? 'Bitte festlegen' : $storedKind) ?></span><?php endif; ?>
        </td></tr>
      <?php endforeach; ?>
      </tbody></table></div>
      <?php if (current_user_is_superadmin()): ?><div class="d-flex justify-content-end mt-3"><button class="btn btn-primary" type="submit"><i class="fa-solid fa-check-double me-1" aria-hidden="true"></i>Alle Positionen übernehmen</button></div></form><?php endif; ?>
    <?php endif; ?>
  </div>
</section>
<?php if (current_user_is_superadmin()): $suggestion = $suggestion ?? ['candidates' => [], 'reason' => '']; $devicePositions = array_values(array_filter($reconciliation['positions'] ?? [], static fn(array $position): bool => in_array((string) $position['kind'], ['device'], true) || ((string) $position['kind'] === 'unclassified' && (string) $position['suggested_kind'] === 'device'))); $regiePositions = array_values(array_filter($reconciliation['positions'] ?? [], static fn(array $position): bool => in_array((string) $position['kind'], ['regie'], true) || ((string) $position['kind'] === 'unclassified' && (string) $position['suggested_kind'] === 'regie'))); ?>
<details class="card mb-4"<?= $suggestion['candidates'] !== [] ? ' open' : '' ?>><summary class="card-header fw-semibold"><i class="fa-solid fa-wand-magic-sparkles me-2" aria-hidden="true"></i>Zuordnungsvorschlag prüfen<?= $suggestion['candidates'] !== [] ? ' · ' . count($suggestion['candidates']) . ' Prüfungen' : '' ?></summary><div class="card-body">
  <p class="small text-body-secondary"><?= htmlspecialchars((string) $suggestion['reason']) ?> Es wird nichts automatisch abgerechnet oder zugeordnet. Mit der bestätigten Sammelzuordnung werden die oben vorgeschlagenen Positionsarten verbindlich gespeichert.</p>
  <?php if ($suggestion['candidates'] !== [] && $devicePositions !== []):
    $remainingRegie = max(0, (int) ($reconciliation['regieTarget'] ?? 0) - (int) ($reconciliation['regieActual'] ?? 0));
    $sourceRegie = array_sum(array_map(static fn(array $candidate): int => (int) ($candidate['regie_minutes'] ?? 0), $suggestion['candidates']));
  ?>
    <?php if ($remainingRegie > 0): ?><div class="alert alert-warning py-2"><strong>Regie-Abweichung prüfen:</strong> Die ausgewählten Phoenix-Importprüfungen enthalten <?= $sourceRegie ?> Min. Regie, die Rechnung weist <?= $remainingRegie ?> Min. aus. Es wird nichts aus der Rechnung auf Prüfungen verteilt. Erst nach einem Import- oder Datenabgleich darf eine zusätzliche Regiezeit bewusst ergänzt werden.</div><?php endif; ?>
    <form method="post" action="<?= htmlspecialchars(url_for('admin/abrechnung/rechnung/' . (int) $invoice->id . '/historisch-zuordnen-sammeln'), ENT_QUOTES) ?>">
      <div class="table-responsive mb-3"><table class="table table-sm align-middle"><thead><tr><th><span class="visually-hidden">Auswahl</span></th><th>Prüfung</th><th>Datum</th><th>Gerät</th><th>Ergebnis</th><th>Regie aus Import</th></tr></thead><tbody>
      <?php foreach ($suggestion['candidates'] as $candidate): ?>
        <tr><td><input class="form-check-input" type="checkbox" name="inspection_ids[]" value="<?= (int) $candidate['id'] ?>" checked aria-label="<?= htmlspecialchars((string) $candidate['external_number'], ENT_QUOTES) ?> zuordnen"></td><td><?= htmlspecialchars((string) $candidate['external_number']) ?></td><td><?= htmlspecialchars((string) $candidate['test_date']) ?></td><td><?= htmlspecialchars((string) $candidate['device_number'] . ' · ' . $candidate['device_name']) ?></td><td><?= htmlspecialchars((string) $candidate['result_status']) ?></td><td><?= (int) $candidate['regie_minutes'] ?> Min.</td></tr>
      <?php endforeach; ?>
      </tbody></table></div>
      <div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label">Als Geräteposition zuordnen</label><select class="form-select" name="device_position_id" required><?php foreach ($devicePositions as $position): ?><option value="<?= (int) $position['id'] ?>"><?= htmlspecialchars((string) $position['position_number'] . ' · ' . $position['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Regieposition</label><select class="form-select" name="regie_position_id"><option value="">Keine Regie zuordnen</option><?php foreach ($regiePositions as $position): ?><option value="<?= (int) $position['id'] ?>"<?= $remainingRegie > 0 && $position === $regiePositions[0] ? ' selected' : '' ?>><?= htmlspecialchars((string) $position['position_number'] . ' · ' . $position['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Bestätigte Rechnungsregie</label><div class="input-group"><input class="form-control" type="number" name="historical_regie_minutes" min="0" value="<?= $remainingRegie ?>" aria-describedby="historical-regie-help"><span class="input-group-text">Min.</span></div></div><div class="col-md-3"><label class="form-check mb-2"><input class="form-check-input" type="checkbox" name="confirm" value="1" required> <span class="form-check-label">Liste und Regie geprüft</span></label><button class="btn btn-primary w-100" type="submit"><i class="fa-solid fa-link me-1" aria-hidden="true"></i>Auswahl gesammelt zuordnen</button></div><div class="col-12"><div class="form-text" id="historical-regie-help">Der Rechnungswert ist vorausgefüllt, weil die geprüfte Phoenix-Quelle keine Einzel-Regie enthält. Erst mit dieser Bestätigung wird er nachvollziehbar auf die ausgewählten Prüfungen verteilt; die Importrohwerte bleiben unverändert.</div></div></div>
    </form>
  <?php elseif ($suggestion['candidates'] !== []): ?><div class="alert alert-warning mb-0">Bitte oben mindestens eine Rechnungsposition als „Geräte“ bestätigen. Danach steht der Sammelvorschlag bereit.</div><?php endif; ?>
</div></details>
<?php endif; ?>
<?php if (current_user_is_superadmin() && ($reconciliation['positions'] ?? []) !== []): ?><details class="card mb-4"><summary class="card-header fw-semibold"><i class="fa-solid fa-link me-2" aria-hidden="true"></i>Historische Prüfung bewusst zuordnen</summary><div class="card-body"><p class="small text-body-secondary">Diese Bestätigung erzeugt eine nachvollziehbare Zuordnung. Nicht eindeutige Fälle bleiben bis dahin offen.</p><form method="post" action="<?= htmlspecialchars(url_for('admin/abrechnung/rechnung/' . (int) $invoice->id . '/historisch-zuordnen'), ENT_QUOTES) ?>" class="row g-3"><div class="col-md-5"><label class="form-label">Prüfung</label><select class="form-select" name="inspection_id" required><option value="">Bitte wählen</option><?php foreach (($candidates ?? []) as $candidate): ?><option value="<?= (int) $candidate['id'] ?>"><?= htmlspecialchars((string) $candidate['external_number'] . ' · ' . $candidate['test_date'] . ' · ' . $candidate['device_number']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Geräteposition</label><select class="form-select" name="device_position_id" required><option value="">Bitte wählen</option><?php foreach ($reconciliation['positions'] as $position): ?><option value="<?= (int) $position['id'] ?>"><?= htmlspecialchars((string) $position['position_number'] . ' · ' . $position['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Regieposition</label><select class="form-select" name="regie_position_id"><option value="">keine</option><?php foreach ($reconciliation['positions'] as $position): ?><option value="<?= (int) $position['id'] ?>"><?= htmlspecialchars((string) $position['position_number'] . ' · ' . $position['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-1"><label class="form-label">Geräte</label><input class="form-control" type="number" name="quantity" min="0" value="1"></div><div class="col-md-1"><label class="form-label">Regie</label><input class="form-control" type="number" name="regie_minutes" min="0" value="0"></div><div class="col-12"><button class="btn btn-primary" type="submit"><i class="fa-solid fa-check me-1" aria-hidden="true"></i>Zuordnung bestätigen</button></div></form></div></details><?php endif; ?>
<?php if (current_user_is_superadmin() && (string) ($invoice->status ?? '') === 'sevdesk' && trim((string) ($invoice->sevdesk_invoice_id ?? '')) !== ''): ?><form method="post" action="<?= htmlspecialchars(url_for('admin/abrechnung/rechnung/' . (int) $invoice->id . '/sevdesk-entwurf-loeschen'), ENT_QUOTES) ?>" class="alert alert-warning d-flex flex-wrap justify-content-between align-items-center gap-2"><div><strong>Entwurf neu erstellen</strong><div class="small">Löscht ausschließlich den noch unveränderten Entwurf in SevDesk und gibt die verknüpften Prüfungen wieder frei. Die Exporthistorie bleibt erhalten.</div></div><input type="hidden" name="confirm" value="1"><button class="btn btn-danger" type="submit" onclick="return confirm('SevDesk-Entwurf wirklich löschen und alle Prüfungen wieder freigeben?');"><i class="fa-solid fa-trash me-1" aria-hidden="true"></i>Entwurf löschen &amp; neu abrechnen</button></form><?php endif; ?>
<h2 class="h5 mt-4">Verknüpfte Prüfungen und Geräte</h2>
<form method="post" action="<?= htmlspecialchars(url_for('geraete/export'), ENT_QUOTES) ?>" class="mb-3 d-flex align-items-end gap-2 flex-wrap"><input type="hidden" name="scope" value="selection"><input type="hidden" name="invoice_id" value="<?= (int) $invoice->id ?>"><label>Max. Seiten<input class="form-control form-control-sm" type="number" name="bundle_max_pages" min="10" max="5000" value="500"></label><button class="btn btn-sm btn-success" name="format" value="bundle_pdf">Sammel-PDF dieser Rechnung erzeugen</button></form>
<div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Gerät</th><th>Prüfung</th><th>Kunde</th><th>Datum</th><th>Zuordnung</th><th>Menge</th></tr></thead><tbody>
<?php foreach ($items as $item): ?><tr><td><a href="<?= htmlspecialchars(url_for('geraete?device_id=' . (int) $item['device_id']), ENT_QUOTES) ?>"><?= htmlspecialchars((string) $item['device_number']) ?> · <?= htmlspecialchars((string) $item['device_name']) ?></a></td><td><a href="<?= htmlspecialchars(url_for('admin/pruefungen/' . (int) $item['inspection_id']), ENT_QUOTES) ?>"><?= htmlspecialchars((string) $item['inspection_number']) ?></a></td><td><?= htmlspecialchars((string) ($item['customer_name'] ?? '—')) ?></td><td><?= htmlspecialchars((string) $item['test_date']) ?></td><td><span class="badge text-bg-<?= !empty($item['active']) ? 'success' : 'secondary' ?>"><?= !empty($item['active']) ? 'aktiv' : 'historisch' ?></span></td><td><?= htmlspecialchars((string) $item['quantity']) ?></td></tr><?php endforeach; ?>
<?php if ($items === []): ?><tr><td colspan="6" class="text-body-secondary">Keine verknüpften Positionen.</td></tr><?php endif; ?></tbody></table></div>
