<?php
$form = static function ($device = null) use ($rooms, $roomLabels): void {
    $device ??= (object) ['id' => 0, 'name' => '', 'room_id' => 0, 'serial_number' => '', 'inventory_number' => '', 'device_model' => '', 'manufacturer' => '', 'warming_device' => 0, 'description' => '', 'comment' => '', 'metadata_json' => '{}'];
    $metadataValue = trim((string) ($device->metadata_json ?? ''));
    if ($metadataValue === '{}') $metadataValue = '';
?>
  <form method="post" action="<?= htmlspecialchars(url_for('geraete'), ENT_QUOTES) ?>" class="row g-2">
    <input type="hidden" name="id" value="<?= (int) $device->id ?>">
    <div class="col-md-2"><label class="form-label">Gerätenummer</label><input class="form-control" value="<?= htmlspecialchars((string) ($device->external_number ?? '')) ?>" readonly></div>
    <div class="col-md-4"><label class="form-label">Gerätebezeichnung</label><input class="form-control" name="name" required value="<?= htmlspecialchars((string) $device->name) ?>"></div>
    <div class="col-md-4"><label class="form-label">Raum</label><select class="form-select" name="room_id" required data-search-select data-placeholder="Raum suchen"><option value="">Raum wählen</option><?php foreach ($rooms as $room): ?><option value="<?= (int) $room->id ?>"<?= (int) $device->room_id === (int) $room->id ? ' selected' : '' ?>><?= htmlspecialchars($roomLabels[(int) $room->id] ?? (string) $room->name) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-2"><label class="form-label">Inventarnummer</label><input class="form-control" name="inventory_number" value="<?= htmlspecialchars((string) $device->inventory_number) ?>"></div>
    <div class="col-md-2"><label class="form-label">Seriennummer</label><input class="form-control" name="serial_number" value="<?= htmlspecialchars((string) $device->serial_number) ?>"></div>
    <div class="col-md-3"><label class="form-label">Typ</label><input class="form-control" name="device_model" value="<?= htmlspecialchars((string) ($device->device_model ?? '')) ?>"></div>
    <div class="col-md-3"><label class="form-label">Hersteller</label><input class="form-control" name="manufacturer" value="<?= htmlspecialchars((string) ($device->manufacturer ?? '')) ?>"></div>
    <div class="col-md-2 form-check mt-4 ms-2"><input class="form-check-input" type="checkbox" name="warming_device" id="warming-<?= (int) $device->id ?>"<?= !empty($device->warming_device) ? ' checked' : '' ?>><label class="form-check-label" for="warming-<?= (int) $device->id ?>">Wärmegerät</label></div>
    <div class="col-12"><label class="form-label">Kurzbeschreibung</label><textarea class="form-control" name="description" rows="2" maxlength="240" placeholder="Funktion, Bauart oder Einsatz des Geräts"><?= htmlspecialchars((string) $device->description) ?></textarea><div class="form-text">Wird direkt in der Geräteübersicht angezeigt, maximal 240 Zeichen.</div></div>
    <div class="col-md-6"><label class="form-label">Kommentar</label><textarea class="form-control" name="comment" placeholder="Interne Hinweise und Bemerkungen"><?= htmlspecialchars((string) $device->comment) ?></textarea></div>
    <div class="col-md-6"><label class="form-label">Metadaten (JSON-Objekt, optional)</label><textarea class="form-control font-monospace" name="metadata_json" placeholder='z. B. {"kostenstelle":"1000"}'><?= htmlspecialchars($metadataValue) ?></textarea></div>
    <div class="col-12 text-end"><button class="btn btn-primary btn-sm">Speichern</button></div>
  </form>
<?php }; ?>

<?php if ($canManage): ?><div class="card mb-4"><div class="card-header"><strong>Neues Gerät</strong></div><div class="card-body"><?php $form(); ?></div></div><?php endif; ?>
<p class="small text-body-secondary"><?= (int) $total ?> Geräte · Seite <?= (int) $page ?> von <?= (int) $pages ?></p>
<div class="vstack gap-3">
<?php foreach ($devices as $device): $deviceInspections = $inspections[(int) $device->id] ?? []; $latestInspection = $deviceInspections[0] ?? null; ?>
  <?php $roomLabel = $roomLabels[(int) $device->room_id] ?? ''; $roomLabel = $roomLabel !== '' ? $roomLabel : (trim((string) ($device->room_snapshot ?? '')) !== '' ? 'historischer Raum ' . (string) $device->room_snapshot : 'ohne Raum'); ?>
  <details class="card"><summary class="card-header"><span class="badge text-bg-secondary me-2"><i class="fa-solid fa-id-card me-1" aria-hidden="true"></i><?= htmlspecialchars((string) ($device->external_number ?: 'ohne Nummer')) ?></span><strong><?= htmlspecialchars((string) $device->name) ?></strong> · <?= htmlspecialchars($roomLabel) ?><?php if ($latestInspection && trim((string) ($latestInspection->report_path ?? '')) !== ''): ?><a class="badge text-bg-danger ms-2 text-decoration-none" href="<?= htmlspecialchars($inspectionReportUrl((int) $latestInspection->id)) ?>" target="_blank" rel="noopener"><i class="fa-solid fa-file-pdf me-1" aria-hidden="true"></i>Bericht</a><?php endif; ?><?php if (trim((string) $device->description) !== ''): ?><span class="d-block small text-body-secondary mt-1"><?= htmlspecialchars((string) $device->description) ?></span><?php endif; ?></summary>
    <div class="card-body"><?php if ($canManage): $form($device); else: ?><p><?= nl2br(htmlspecialchars((string) $device->comment)) ?></p><?php endif; ?>
      <?php if (trim((string) ($device->external_number ?? '')) !== '' || trim((string) ($device->storage_slot ?? '')) !== ''): ?><p class="small text-body-secondary mb-2">Gerätenummer: <?= htmlspecialchars((string) ($device->external_number ?? '')) ?><?php if (trim((string) ($device->legacy_number ?? '')) !== ''): ?> · alte Nummer: <?= htmlspecialchars((string) $device->legacy_number) ?><?php endif; ?><?php if (trim((string) ($device->storage_slot ?? '')) !== ''): ?> · Speicherplatz: <?= htmlspecialchars((string) $device->storage_slot) ?><?php endif; ?></p><?php endif; ?>
      <?php if ($deviceInspections): ?><h2 class="h6 mt-3">Prüfungen</h2><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Prüfnummer</th><th>Datum</th><th>Prüfart</th><th>Prüfer</th><th>Nächste Prüfung</th><th>Ergebnis</th><th>Raum</th><th>Bericht</th></tr></thead><tbody><?php foreach ($deviceInspections as $inspection): $raw = json_decode((string) ($inspection->raw_json ?? ''), true) ?: []; ?><tr><td><?= htmlspecialchars((string) ($inspection->external_number ?: '—')) ?></td><td><?= htmlspecialchars((string) ($inspection->test_date ?: '—')) ?></td><td><?= htmlspecialchars((string) ($raw['type'] ?? $inspection->device_type ?? '—')) ?></td><td><?= htmlspecialchars((string) ($raw['created_by'] ?? '—')) ?></td><td><?= htmlspecialchars((string) ($inspection->next_due_date ?: '—')) ?></td><td><?= htmlspecialchars((string) ($inspection->result_status ?: 'unbekannt')) ?></td><td><?= htmlspecialchars((string) ($inspection->room_snapshot ?: '—')) ?></td><td><?php if (trim((string) ($inspection->report_path ?? '')) !== ''): ?><a href="<?= htmlspecialchars($inspectionReportUrl((int) $inspection->id)) ?>" target="_blank" rel="noopener">PDF</a><?php else: ?>—<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
    </div>
  </details>
<?php endforeach; ?>
</div>
<?php if ($pages > 1): ?><nav aria-label="Geräteseiten" class="mt-4"><ul class="pagination justify-content-center flex-wrap"><li class="page-item<?= $page <= 1 ? ' disabled' : '' ?>"><a class="page-link" href="<?= htmlspecialchars(url_for('geraete?page=' . max(1, $page - 1)), ENT_QUOTES) ?>">Zurück</a></li><?php for ($number = 1; $number <= $pages; $number++): ?><?php if ($number === 1 || $number === $pages || abs($number - $page) <= 2): ?><li class="page-item<?= $number === $page ? ' active' : '' ?>"><a class="page-link" href="<?= htmlspecialchars(url_for('geraete?page=' . $number), ENT_QUOTES) ?>"><?= $number ?></a></li><?php elseif ($number === 2 || $number === $pages - 1): ?><li class="page-item disabled"><span class="page-link">…</span></li><?php endif; ?><?php endfor; ?><li class="page-item<?= $page >= $pages ? ' disabled' : '' ?>"><a class="page-link" href="<?= htmlspecialchars(url_for('geraete?page=' . min($pages, $page + 1)), ENT_QUOTES) ?>">Weiter</a></li></ul></nav><?php endif; ?>
