<?php
/** @var int $deviceId */
/** @var list<array<string,mixed>> $media */
$media = $media ?? [];
$canManageMedia = $canManageMedia ?? false;
$panelId = 'device-media-panel-' . (int) $deviceId;
?>
<details class="card mt-3" id="<?= $panelId ?>">
  <summary class="card-header fw-semibold"><i class="fa-solid fa-camera me-2" aria-hidden="true"></i>Fotodokumentation <span class="small text-body-secondary fw-normal">optional</span></summary>
  <div class="card-body">
    <p class="small text-body-secondary">Fotos sind optional. Fotoart und Bemerkung lassen sich nach dem Upload direkt ändern. Typenschildfotos können zusätzlich ausgewertet werden; die KI füllt nichts automatisch aus.</p>
    <?php if ($media !== []): ?><div class="row g-3 mb-3"><?php foreach ($media as $photo): $proposal = json_decode((string) ($photo['proposal_json'] ?? ''), true); $proposal = is_array($proposal) ? $proposal : []; ?>
      <div class="col-12 col-md-6 col-xl-4"><?= render_template('media_photo_card.php', ['photo' => $photo, 'panelId' => $panelId, 'canManageMedia' => $canManageMedia, 'allowTypePlate' => true]) ?>
      <?php if ((string) $photo['media_type'] === 'type_plate' && $canManageMedia): ?><div class="mt-2" hx-indicator="#media-analysis-spinner-<?= (int) $photo['id'] ?>"><?php if (($photo['analysis_status'] ?? '') === 'done'): ?><div class="alert alert-success py-2 small mb-2"><i class="fa-solid fa-wand-magic-sparkles me-1" aria-hidden="true"></i>Vorschlag bereit<?php if (($proposal['confidence'] ?? null) !== null): ?> · <?= (int) round((float) $proposal['confidence'] * 100) ?> %<?php endif; ?><div class="mt-1"><?php foreach (['manufacturer' => 'Hersteller', 'device_model' => 'Typ/Modell', 'name' => 'Gerät', 'serial_number' => 'Seriennummer', 'inventory_number' => 'Inventar'] as $key => $label): if (trim((string) ($proposal[$key] ?? '')) !== ''): ?><div><?= htmlspecialchars($label) ?>: <strong><?= htmlspecialchars((string) $proposal[$key]) ?></strong></div><?php endif; endforeach; ?></div></div><button class="btn btn-sm btn-primary mb-2" type="button" data-apply-typeplate='<?= htmlspecialchars(json_encode($proposal, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES), ENT_QUOTES) ?>'><i class="fa-solid fa-arrow-down me-1" aria-hidden="true"></i>Vorschlag in Formular übernehmen</button><?php elseif (($photo['analysis_status'] ?? '') === 'failed'): ?><div class="alert alert-warning py-2 small mb-2"><?= htmlspecialchars((string) ($photo['error_message'] ?: 'Typenschild konnte nicht ausgewertet werden.')) ?></div><?php endif; ?><button class="btn btn-sm btn-primary" type="button" hx-post="<?= htmlspecialchars(url_for('geraete/fotos/' . (int) $photo['id'] . '/typenschild-analysieren'), ENT_QUOTES) ?>" hx-target="#<?= $panelId ?>" hx-swap="outerHTML"><i class="fa-solid fa-wand-magic-sparkles me-1" aria-hidden="true"></i>Typenschild erkennen <span class="spinner-border spinner-border-sm htmx-indicator" id="media-analysis-spinner-<?= (int) $photo['id'] ?>" aria-hidden="true"></span></button></div><?php endif; ?></div>
    <?php endforeach; ?></div><?php endif; ?>
    <?php if ($canManageMedia): ?><?= render_template('media_upload_component.php', ['componentId' => 'device-photo-' . (int) $deviceId, 'action' => url_for('geraete/' . (int) $deviceId . '/fotos'), 'hxTarget' => '#' . $panelId, 'allowTypePlate' => true, 'contextHint' => 'Bild und Bemerkung werden diesem Gerät zugeordnet.']) ?><?php endif; ?>
  </div>
</details>
<style>.media-thumb{width:100%;height:10rem;object-fit:cover;background:var(--bs-tertiary-bg)}.htmx-indicator{display:none}.htmx-request .htmx-indicator,.htmx-request.htmx-indicator{display:inline-block}</style>
<script>(() => { document.querySelectorAll('[data-apply-typeplate]').forEach(button => { if (button.dataset.bound) return; button.dataset.bound = '1'; button.addEventListener('click', () => { let proposal; try { proposal = JSON.parse(button.dataset.applyTypeplate || '{}'); } catch (_) { return; } const form = button.closest('details.device-card')?.querySelector('form.device-form'); if (!form) return; ['manufacturer','device_model','name','serial_number','inventory_number'].forEach(key => { const value = String(proposal[key] || '').trim(); const field = form.querySelector(`[name="${key}"]`); if (value && field) { field.value = value; field.dispatchEvent(new Event('change', {bubbles:true})); } }); form.scrollIntoView({behavior:'smooth', block:'center'}); }); }); })();</script>
