<?php
/** @var int $deviceId */
/** @var list<array<string,mixed>> $media */
$media = $media ?? [];
$canManageMedia = $canManageMedia ?? false;
$labels = ['type_plate' => 'Typenschild', 'condition' => 'Zustand', 'defect' => 'Mangel', 'disposal' => 'Aussonderung', 'other' => 'Sonstiges'];
?>
<details class="card mt-3" id="device-media-panel-<?= (int) $deviceId ?>">
  <summary class="card-header fw-semibold"><i class="fa-solid fa-camera me-2" aria-hidden="true"></i>Fotodokumentation <span class="small text-body-secondary fw-normal">optional</span></summary>
  <div class="card-body">
    <p class="small text-body-secondary">Fotos sind optional. Typenschildfotos können direkt ausgewertet werden; die KI füllt nichts automatisch aus.</p>
    <?php if ($media !== []): ?><div class="row g-3 mb-3"><?php foreach ($media as $photo): $proposal = json_decode((string) ($photo['proposal_json'] ?? ''), true); $proposal = is_array($proposal) ? $proposal : []; ?>
      <div class="col-12 col-md-6 col-xl-4"><article class="border rounded-3 p-2 h-100"><a href="<?= htmlspecialchars(url_for('geraete/fotos/' . (int) $photo['id']), ENT_QUOTES) ?>" target="_blank" rel="noopener"><img class="img-fluid rounded media-thumb" src="<?= htmlspecialchars(url_for('geraete/fotos/' . (int) $photo['id']), ENT_QUOTES) ?>" alt="<?= htmlspecialchars((string) ($photo['caption'] ?: $labels[(string) $photo['media_type']] ?? 'Foto'), ENT_QUOTES) ?>"></a><div class="small fw-semibold mt-2"><i class="fa-solid <?= (string) $photo['media_type'] === 'type_plate' ? 'fa-id-card' : 'fa-camera' ?> me-1" aria-hidden="true"></i><?= htmlspecialchars($labels[(string) $photo['media_type']] ?? 'Foto') ?></div><?php if (trim((string) $photo['caption']) !== ''): ?><div class="small text-body-secondary"><?= htmlspecialchars((string) $photo['caption']) ?></div><?php endif; ?>
      <?php if ((string) $photo['media_type'] === 'type_plate' && $canManageMedia): ?><div class="mt-2" hx-indicator="#media-analysis-spinner-<?= (int) $photo['id'] ?>"><?php if (($photo['analysis_status'] ?? '') === 'done'): ?><div class="alert alert-success py-2 small mb-2"><i class="fa-solid fa-wand-magic-sparkles me-1" aria-hidden="true"></i>Vorschlag bereit<?php if (($proposal['confidence'] ?? null) !== null): ?> · <?= (int) round((float) $proposal['confidence'] * 100) ?> %<?php endif; ?><div class="mt-1"><?php foreach (['manufacturer' => 'Hersteller', 'device_model' => 'Typ/Modell', 'name' => 'Gerät', 'serial_number' => 'Seriennummer', 'inventory_number' => 'Inventar'] as $key => $label): if (trim((string) ($proposal[$key] ?? '')) !== ''): ?><div><?= htmlspecialchars($label) ?>: <strong><?= htmlspecialchars((string) $proposal[$key]) ?></strong></div><?php endif; endforeach; ?></div></div><button class="btn btn-sm btn-primary mb-2" type="button" data-apply-typeplate='<?= htmlspecialchars(json_encode($proposal, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES), ENT_QUOTES) ?>'><i class="fa-solid fa-arrow-down me-1" aria-hidden="true"></i>Vorschlag in Formular übernehmen</button><?php elseif (($photo['analysis_status'] ?? '') === 'failed'): ?><div class="alert alert-warning py-2 small mb-2"><?= htmlspecialchars((string) ($photo['error_message'] ?: 'Typenschild konnte nicht ausgewertet werden.')) ?></div><?php endif; ?><button class="btn btn-sm btn-primary" type="button" hx-post="<?= htmlspecialchars(url_for('geraete/fotos/' . (int) $photo['id'] . '/typenschild-analysieren'), ENT_QUOTES) ?>" hx-target="#device-media-panel-<?= (int) $deviceId ?>" hx-swap="outerHTML"><i class="fa-solid fa-wand-magic-sparkles me-1" aria-hidden="true"></i>Typenschild erkennen <span class="spinner-border spinner-border-sm htmx-indicator" id="media-analysis-spinner-<?= (int) $photo['id'] ?>" aria-hidden="true"></span></button></div><?php endif; ?>
      <?php if ($canManageMedia): ?><button class="btn btn-sm btn-outline-danger mt-2" type="button" hx-post="<?= htmlspecialchars(url_for('geraete/fotos/' . (int) $photo['id'] . '/loeschen'), ENT_QUOTES) ?>" hx-target="#device-media-panel-<?= (int) $deviceId ?>" hx-swap="outerHTML" hx-confirm="Foto wirklich löschen?"><i class="fa-solid fa-trash me-1" aria-hidden="true"></i>Löschen</button><?php endif; ?></article></div>
    <?php endforeach; ?></div><?php endif; ?>
    <?php if ($canManageMedia): ?><?= render_template('media_upload_component.php', ['componentId' => 'device-photo-' . (int) $deviceId, 'action' => url_for('geraete/' . (int) $deviceId . '/fotos'), 'hxTarget' => '#device-media-panel-' . (int) $deviceId, 'allowTypePlate' => true]) ?><?php endif; ?>
  </div>
</details>
<style>.media-thumb{width:100%;height:10rem;object-fit:cover;background:var(--bs-tertiary-bg)}.htmx-indicator{display:none}.htmx-request .htmx-indicator,.htmx-request.htmx-indicator{display:inline-block}</style>
<script>(() => { document.querySelectorAll('[data-apply-typeplate]').forEach(button => { if (button.dataset.bound) return; button.dataset.bound = '1'; button.addEventListener('click', () => { let proposal; try { proposal = JSON.parse(button.dataset.applyTypeplate || '{}'); } catch (_) { return; } const form = button.closest('details.device-card')?.querySelector('form.device-form'); if (!form) return; ['manufacturer','device_model','name','serial_number','inventory_number'].forEach(key => { const value = String(proposal[key] || '').trim(); const field = form.querySelector(`[name="${key}"]`); if (value && field) { field.value = value; field.dispatchEvent(new Event('change', {bubbles:true})); } }); const cable = form.querySelector('[name="cable_length_m"]'); if (cable && proposal.cable_length_m !== null && proposal.cable_length_m !== undefined) cable.value = proposal.cable_length_m; const warming = form.querySelector('[name="warming_device"]'); if (warming && proposal.warming_device !== null) warming.checked = !!proposal.warming_device; form.scrollIntoView({behavior:'smooth', block:'center'}); }); }); })();</script>
