<div class="card shadow-sm"><div class="card-body">
  <h1 class="h4"><i class="fa-solid fa-stairs me-2" aria-hidden="true"></i>Leiterprüfung</h1>
  <p class="text-body-secondary mb-4">Gerät: <strong><?= htmlspecialchars((string) $device->external_number) ?> · <?= htmlspecialchars((string) $device->name) ?></strong></p>
  <?php if ($error !== null): ?><div class="alert alert-danger"><i class="fa-solid fa-triangle-exclamation me-1" aria-hidden="true"></i><?= htmlspecialchars($error) ?></div><?php endif; ?>
  <?= render_template('inspection_media_panel.php', ['inspection' => $inspection, 'inspectionMedia' => $inspectionMedia ?? []]) ?>
  <form method="post" class="row g-3">
    <div class="col-md-4"><label class="form-label"><i class="fa-solid fa-calendar-day me-1" aria-hidden="true"></i>Prüfdatum</label><input class="form-control" type="date" name="test_date" value="<?= htmlspecialchars((string) $inspection->test_date) ?>" required></div>
    <div class="col-md-4"><label class="form-label"><i class="fa-solid fa-calendar-check me-1" aria-hidden="true"></i>Nächste Prüfung</label><input class="form-control" type="date" name="next_due_date" value="<?= htmlspecialchars((string) $inspection->next_due_date) ?>" required></div>
    <div class="col-md-4"><label class="form-label"><i class="fa-solid fa-user-check me-1" aria-hidden="true"></i>Prüfer</label><input class="form-control" value="<?= htmlspecialchars(display_examiner_name((string) $inspection->examiner)) ?>" disabled></div>
    <div class="col-12"><h2 class="h5 border-bottom pb-2"><i class="fa-solid fa-ruler-combined me-2" aria-hidden="true"></i>Leiterdaten</h2></div>
    <?php foreach (InspectionTypeService::attributeDefinitions(InspectionTypeService::LADDER) as $key => $definition): ?><div class="col-md-4"><label class="form-label" for="attribute-<?= htmlspecialchars($key) ?>"><?= htmlspecialchars($definition['label']) ?></label><?php if ($definition['type'] === 'select'): ?><select class="form-select" id="attribute-<?= htmlspecialchars($key) ?>" name="attributes[<?= htmlspecialchars($key) ?>]"><option value="">Bitte wählen</option><?php foreach ($definition['options'] as $value => $label): ?><option value="<?= htmlspecialchars($value) ?>"<?= (string) ($attributes[$key] ?? '') === $value ? ' selected' : '' ?>><?= htmlspecialchars($label) ?></option><?php endforeach; ?></select><?php else: ?><input class="form-control" id="attribute-<?= htmlspecialchars($key) ?>" type="<?= $definition['type'] === 'number' ? 'number' : ($definition['type'] === 'date' ? 'date' : 'text') ?>" name="attributes[<?= htmlspecialchars($key) ?>]" value="<?= htmlspecialchars((string) ($attributes[$key] ?? '')) ?>"<?= $definition['type'] === 'number' ? ' step="any"' : '' ?>><?php endif; ?></div><?php endforeach; ?>
    <div class="col-12"><h2 class="h5 border-bottom pb-2"><i class="fa-solid fa-list-check me-2" aria-hidden="true"></i>Prüfpunkte</h2></div>
    <?php foreach ($catalog as $item): $key = (string) $item['item_key']; $answer = $answersByKey[$key] ?? []; $value = (string) ($answer['answer_value'] ?? ''); ?><div class="col-12"><div class="border rounded p-3"><div class="d-flex flex-wrap justify-content-between gap-2"><div><strong><?= htmlspecialchars((string) $item['category']) ?></strong><div><?= htmlspecialchars((string) $item['question']) ?></div><div class="small text-body-secondary"><?= htmlspecialchars((string) $item['criterion']) ?></div></div><div class="btn-group" role="group" aria-label="Bewertung"><input class="btn-check" type="radio" id="<?= $key ?>-ok" name="finding[<?= $key ?>]" value="ok"<?= $value === 'ok' ? ' checked' : '' ?>><label class="btn btn-outline-success" for="<?= $key ?>-ok">In Ordnung</label><input class="btn-check" type="radio" id="<?= $key ?>-green" name="finding[<?= $key ?>]" value="green"<?= $value === 'green' ? ' checked' : '' ?>><label class="btn btn-outline-success" for="<?= $key ?>-green">Hinweis · Grün</label><input class="btn-check" type="radio" id="<?= $key ?>-orange" name="finding[<?= $key ?>]" value="orange"<?= $value === 'orange' ? ' checked' : '' ?>><label class="btn btn-outline-warning" for="<?= $key ?>-orange">Mangel · Orange</label><input class="btn-check" type="radio" id="<?= $key ?>-red" name="finding[<?= $key ?>]" value="red"<?= $value === 'red' ? ' checked' : '' ?>><label class="btn btn-outline-danger" for="<?= $key ?>-red">Mangel · Rot</label></div></div><input class="form-control mt-2" name="remark[<?= htmlspecialchars($key) ?>]" placeholder="Bemerkung / Kundenhinweis" value="<?= htmlspecialchars((string) ($answer['remark'] ?? '')) ?>"></div></div><?php endforeach; ?>
    <div class="col-md-6"><label class="form-label"><i class="fa-solid fa-comment me-1" aria-hidden="true"></i>Allgemeine Bemerkung</label><textarea class="form-control" name="metadata_notes" rows="3"><?= htmlspecialchars((string) $inspection->metadata_notes) ?></textarea></div>
    <div class="col-md-6"><label class="form-label"><i class="fa-solid fa-comment-dots me-1" aria-hidden="true"></i>Kundenhinweis</label><textarea class="form-control" name="customer_hint" rows="3" placeholder="Wird am Gerät nachverfolgt."><?= htmlspecialchars((string) ($inspection->customer_hint ?? '')) ?></textarea></div>
    <div class="col-md-6"><label class="form-label"><i class="fa-solid fa-screwdriver-wrench me-1" aria-hidden="true"></i>Maßnahme bei nicht bestanden</label><select class="form-select" name="failed_action"><option value="">Nur bei Orange/Rot auswählen</option><option value="blocked"<?= (string) $inspection->failed_action === 'blocked' ? ' selected' : '' ?>>Gesperrt</option><option value="repair"<?= (string) $inspection->failed_action === 'repair' ? ' selected' : '' ?>>Zur Reparatur</option><option value="disposed"<?= (string) $inspection->failed_action === 'disposed' ? ' selected' : '' ?>>Entsorgt</option></select></div>
    <div class="col-12 text-end"><button class="btn btn-outline-primary" type="submit"><i class="fa-solid fa-floppy-disk me-1" aria-hidden="true"></i>Zwischenspeichern</button><button class="btn btn-primary ms-2" name="complete" value="1" type="submit"><i class="fa-solid fa-circle-check me-1" aria-hidden="true"></i>Prüfung abschließen</button></div>
  </form>
</div></div>
