<div class="card" id="inspection-import-panel">
  <div class="card-body">
    <div class="d-flex justify-content-between align-items-center gap-2 flex-wrap"><h1 class="h4 mb-0">Elektro-Prüfungen importieren</h1><label class="small"><input class="form-check-input me-1" type="checkbox" id="import-auto-refresh"> Importstatus automatisch aktualisieren</label></div>
    <?php if (!empty($cron['healthy'])): ?><div class="alert alert-success py-2">Cron letzter Lauf: <?= htmlspecialchars((string) $cron['last_run']) ?></div><?php else: ?><div class="alert alert-warning py-2">Warnung: Der Phoenix-Cron wurde seit mehr als 5 Minuten nicht ausgeführt<?= !empty($cron['last_run']) ? ' (letzter Lauf: ' . htmlspecialchars((string) $cron['last_run']) . ')' : '' ?>.</div><?php endif; ?>
    <?php if (!empty($pendingMeasurementsByDate)): ?><details class="mb-3" open><summary><strong>Messdaten noch importieren</strong> (<?= array_sum(array_map('count', $pendingMeasurementsByDate)) ?> Prüfungen)</summary><div class="small text-body-secondary mt-2">Für diese manuellen Prüfungen fehlen noch Messwerte. Nach dem Import werden die Prüfungen automatisch vervollständigt.</div><?php foreach ($pendingMeasurementsByDate as $pendingDate => $pendingRows): ?><div class="d-flex justify-content-between align-items-center mt-3"><h3 class="h6 mb-0">Prüfdatum <?= htmlspecialchars((string) $pendingDate) ?></h3><a class="btn btn-sm btn-outline-primary" href="#pair-upload" data-import-date="<?= htmlspecialchars((string) $pendingDate, ENT_QUOTES) ?>">CSV/ODS für dieses Datum hochladen</a></div><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Prüfung</th><th>Gerät</th><th>Speicherplatz</th><th></th></tr></thead><tbody><?php foreach ($pendingRows as $pending): ?><tr><td><a href="<?= htmlspecialchars(url_for('admin/pruefungen/' . (int) $pending['inspection_id']), ENT_QUOTES) ?>"><?= htmlspecialchars((string) ($pending['inspection_number'] ?: '—')) ?></a></td><td><a href="<?= htmlspecialchars(url_for('geraete?device_id=' . (int) $pending['device_id']), ENT_QUOTES) ?>"><?= htmlspecialchars(trim((string) $pending['number'] . ' · ' . (string) $pending['name'])) ?></a></td><td><?= htmlspecialchars((string) ($pending['storage_slot'] ?: '—')) ?></td><td><a class="btn btn-sm btn-outline-primary" href="<?= htmlspecialchars(url_for('admin/pruefungen/' . (int) $pending['inspection_id'] . '/bearbeiten'), ENT_QUOTES) ?>">Prüfung öffnen</a></td></tr><?php endforeach; ?></tbody></table></div><?php endforeach; ?></details><?php endif; ?>
    <?php if (!empty($jobs)): ?><details class="mb-3" open><summary><strong>Import-Jobs</strong> (<?= count($jobs) ?>)</summary><div class="table-responsive mt-2"><table class="table table-sm"><thead><tr><th>ID</th><th>Status</th><th>Kunde</th><th>Fortschritt</th><th>Gerät</th><th>Details</th><th></th></tr></thead><tbody><?php foreach ($jobs as $job): $jobId=(string)($job['id']??''); $jobRunning=in_array(($job['state']??''), ['queued','running'], true); ?><tr data-phoenix-job="<?= htmlspecialchars($jobId, ENT_QUOTES) ?>"><td><a href="<?= htmlspecialchars(url_for('admin/pruefungen/import?phoenix_job=' . rawurlencode($jobId)), ENT_QUOTES) ?>" title="Job öffnen"><?= htmlspecialchars($jobId) ?></a></td><td class="job-state"><?= htmlspecialchars((string) ($job['state'] ?? '')) ?></td><td><?= htmlspecialchars((string) ($job['customer_id'] ?? '')) ?></td><td class="job-progress"><?php if (($job['total'] ?? 0) > 0): ?><?= (int) ($job['step'] ?? 0) ?> / <?= (int) $job['total'] ?><?php else: ?>—<?php endif; ?></td><td class="job-device"><?= htmlspecialchars((string) ($job['current_device'] ?? '')) ?></td><td><details<?= $jobRunning ? ' open' : '' ?>><summary>anzeigen</summary><div class="small text-body-secondary job-message"><?= htmlspecialchars((string) ($job['message'] ?? '')) ?></div><pre class="small mb-0 job-details"><?= htmlspecialchars((string) json_encode($job['stats'] ?? ($job['error'] ?? ''), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)) ?></pre></details></td><td><?php if ($jobRunning): ?><form method="post" action="<?= htmlspecialchars(url_for('admin/pruefungen/import/' . rawurlencode($jobId) . '/abbrechen'), ENT_QUOTES) ?>" onsubmit="return confirm('Diesen Import wirklich abbrechen? Bereits importierte Datensätze bleiben erhalten.');"><button class="btn btn-sm btn-outline-danger">Abbrechen</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></details><?php endif; ?>
    <?php if (!empty($importLogs)): ?><details class="mb-3"><summary><strong>Letzte Importe</strong> (<?= count($importLogs) ?>)</summary><div class="mt-2"><?php foreach ($importLogs as $log): $logStats=$log['stats']??[]; ?><details class="border rounded p-2 mb-2"><summary><?= htmlspecialchars((string) ($log['type'] ?? 'Import')) ?> · <?= htmlspecialchars((string) ($log['created_at'] ?? '')) ?> · <?= (int) ($logStats['imported'] ?? 0) ?> Prüfungen</summary><div class="small mt-2">Neu: <?= (int) ($logStats['devices'] ?? 0) ?> Geräte · Aktualisiert: <?= (int) ($logStats['updated'] ?? 0) ?> Prüfungen · Übersprungen: <?= (int) ($logStats['skipped'] ?? 0) ?></div><?php foreach (['new_devices' => 'Neue Geräte', 'updated_devices' => 'Aktualisierte Geräte'] as $listKey => $listLabel): if (!empty($logStats[$listKey])): ?><div class="small mt-2"><strong><?= $listLabel ?>:</strong> <?php foreach ($logStats[$listKey] as $device): ?><a class="me-2" href="<?= htmlspecialchars(url_for('geraete?device_id=' . (int) $device['id']), ENT_QUOTES) ?>"><?= htmlspecialchars((string) ($device['number'] ?? '')) ?></a><?php endforeach; ?></div><?php endif; endforeach; ?><details class="mt-2"><summary>Debug-Log anzeigen</summary><pre class="small mb-0 mt-2"><?= htmlspecialchars((string) json_encode($logStats, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)) ?></pre></details></details><?php endforeach; ?></div></details><?php endif; ?>
    <details class="mb-3"><summary><strong>Messdaten zu bestehender Prüfung importieren</strong></summary><form method="post" enctype="multipart/form-data" class="row g-2 mt-2"><input type="hidden" name="action" value="pending_measurement_import"><div class="col-md-4"><label class="form-label">Prüfdatum</label><input class="form-control" type="date" name="measurement_date" required></div><div class="col-md-5"><label class="form-label">Messdaten (CSV)</label><input class="form-control" type="file" name="measurement_csv" accept=".csv" required></div><div class="col-md-3 d-flex align-items-end"><button class="btn btn-primary w-100">Messdaten importieren</button></div><div class="col-12 form-text">Aktualisiert ausschließlich bestehende Prüfungen mit passendem Prüfdatum und Speicherplatz.</div></form></details>
    <?php foreach (($importLogs ?? []) as $historyLog): $historyStats = $historyLog['stats'] ?? []; if (empty($historyStats['updated_inspections'])) continue; ?><details class="mb-3"><summary>Nachbearbeitung aus Import vom <?= htmlspecialchars((string) ($historyLog['created_at'] ?? ''), ENT_QUOTES) ?></summary><ul class="mt-2 mb-0"><?php foreach ($historyStats['updated_inspections'] as $historyInspection): ?><li><a href="<?= htmlspecialchars(url_for('admin/pruefungen/' . (int) ($historyInspection['id'] ?? 0)), ENT_QUOTES) ?>"><?= htmlspecialchars((string) ($historyInspection['number'] ?? 'Prüfung')) ?></a> · <?= htmlspecialchars((string) ($historyInspection['status'] ?? 'ausstehend')) ?></li><?php endforeach; ?></ul></details><?php endforeach; ?>
    <p class="text-body-secondary">Importe aus JSON/JSONL, CSV/ODS und Phoenix werden hier zentral verarbeitet. Das Verzeichnis kann sowohl ältere JSON/JSONL-Dateien als auch CSV/ODS-Paare enthalten. Detailausgaben stehen nur noch im Debug-Bereich.</p>
    <?php if (is_array($stats)): ?><div class="row g-2 mb-3"><?php foreach (['files' => 'Dateien', 'imported' => 'Prüfungen neu', 'updated' => 'Prüfungen aktualisiert', 'devices' => 'Geräte neu', 'reports' => 'Berichte', 'skipped' => 'Übersprungen'] as $key => $label): ?><div class="col-6 col-md-2"><div class="border rounded p-2 text-center"><div class="small text-body-secondary"><?= $label ?></div><strong><?= (int) ($stats[$key] ?? 0) ?></strong></div></div><?php endforeach; ?></div><details class="mb-3"><summary>Debug-Output anzeigen</summary><pre class="small mt-2"><?= htmlspecialchars((string) json_encode($stats, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)) ?></pre></details><?php endif; ?>
    <?php if ($message !== null): ?><div class="alert alert-info"><?= htmlspecialchars($message) ?></div><?php endif; ?>
    <form method="post" class="row g-2">
      <input type="hidden" name="action" value="directory_import_job">
      <div class="col-md-6"><label class="form-label" for="directory">Importverzeichnis</label><input class="form-control" id="directory" name="directory" required placeholder="/home/codexuser/Elektro-Testdaten"><div class="form-text">JSON/JSONL-Dateien und CSV/ODS-Paare.</div></div><div class="col-md-6"><label class="form-label" for="reports_directory">PDF-Quellverzeichnis (optional)</label><input class="form-control" id="reports_directory" name="reports_directory" placeholder="/var/www/berichte"><div class="form-text">PDF-Dateien werden über die führende Prüfnummer zugeordnet.</div></div>
      <div class="col-md-4"><label class="form-label" for="directory_default_inspection_type">Prüfart für fehlende Angaben</label><input class="form-control" id="directory_default_inspection_type" name="default_inspection_type" placeholder="z. B. Wiederholungsprüfung SK1"></div>
      <div class="col-md-4"><label class="form-label" for="directory_default_examiner">Prüfer für fehlende Angaben</label><select class="form-select" id="directory_default_examiner" name="default_examiner"><option value="">Bitte wählen</option><?php foreach (($examinerUsers ?? []) as $examinerUser): ?><option value="<?= htmlspecialchars((string) $examinerUser['value'], ENT_QUOTES) ?>"><?= htmlspecialchars((string) $examinerUser['label']) ?></option><?php endforeach; ?></select></div>
      <div class="col-md-4"><label class="form-label" for="directory_default_next_due_offset_days">Tage bis zur nächsten Prüfung</label><div class="input-group"><input class="form-control" id="directory_default_next_due_offset_days" name="default_next_due_offset_days" type="number" min="1" step="1" placeholder="z. B. 365"><button class="btn btn-outline-secondary" type="button" onclick="document.getElementById('directory_default_next_due_offset_days').value=365">365</button><button class="btn btn-outline-secondary" type="button" onclick="document.getElementById('directory_default_next_due_offset_days').value=730">730</button></div><div class="form-text">Wird relativ zum jeweiligen Prüfdatum berechnet.</div></div>
      <div class="col-12"><button class="btn btn-primary">Import starten</button></div>
    </form>
    <details class="mb-3" id="pair-upload-panel"><summary><strong>Aktuelle Prüfung als Paar hochladen</strong></summary>
    <h2 class="h6 mt-3">Aktuelle Prüfung als Paar hochladen</h2>
    <p class="text-body-secondary">CSV und ODS müssen denselben Dateinamen haben, zum Beispiel <code>AK_Elektro-26_04_02.csv</code> und <code>AK_Elektro-26_04_02.ods</code>.</p>
    <form method="post" enctype="multipart/form-data" class="row g-2" id="pair-upload">
      <div class="col-md-6"><label class="form-label" for="csv">Messdaten (CSV)</label><input class="form-control" id="csv" name="csv" type="file" accept=".csv" required></div>
      <div class="col-md-6"><label class="form-label" for="ods">Gerätedaten (ODS)</label><input class="form-control" id="ods" name="ods" type="file" accept=".ods" required></div>
      <div class="col-md-4"><label class="form-label" for="default_inspection_type">Prüfart für fehlende Angaben</label><input class="form-control" id="default_inspection_type" name="default_inspection_type" placeholder="z. B. Wiederholungsprüfung SK1"></div>
      <div class="col-md-4"><label class="form-label" for="default_examiner">Prüfer für fehlende Angaben</label><select class="form-select" id="default_examiner" name="default_examiner"><option value="">Bitte wählen</option><?php foreach (($examinerUsers ?? []) as $examinerUser): ?><option value="<?= htmlspecialchars((string) $examinerUser['value'], ENT_QUOTES) ?>"><?= htmlspecialchars((string) $examinerUser['label']) ?></option><?php endforeach; ?></select></div>
      <div class="col-md-4"><label class="form-label" for="default_next_due_offset_days">Tage bis zur nächsten Prüfung</label><div class="input-group"><input class="form-control" id="default_next_due_offset_days" name="default_next_due_offset_days" type="number" min="1" step="1" placeholder="z. B. 365"><button class="btn btn-outline-secondary" type="button" onclick="setNextAudit(365)">365 Tage</button><button class="btn btn-outline-secondary" type="button" onclick="setNextAudit(730)">730 Tage</button></div><div class="form-text">Wird relativ zum jeweiligen Prüfdatum berechnet.</div></div>
      <div class="col-md-4"><label class="form-label" for="default_test_date">Prüfdatum der Messdaten (optional)</label><input class="form-control" id="default_test_date" name="default_test_date" type="date"><div class="form-text">Überschreibt das Datum aus der Datei, wenn gesetzt.</div></div>
      <div class="col-12"><button class="btn btn-primary">Paar importieren</button></div>
      <div class="col-12 mt-3"><label class="form-label">Regeln für Raum/Gerät</label><div id="import-rules"><div class="row g-2 import-rule mb-2"><div class="col-md-2"><input class="form-control rule-room" placeholder="Raum, z. B. K203"></div><div class="col-md-2"><input class="form-control rule-device" placeholder="Gerät/Bezeichnung"></div><div class="col-md-2"><input class="form-control rule-number" placeholder="Gerätenummer (optional)"></div><div class="col-md-2"><input class="form-control rule-type" placeholder="Prüfart"></div><div class="col-md-2"><select class="form-select rule-examiner"><option value="">Prüfer</option><?php foreach (($examinerUsers ?? []) as $examinerUser): ?><option value="<?= htmlspecialchars((string) $examinerUser['value'], ENT_QUOTES) ?>"><?= htmlspecialchars((string) $examinerUser['label']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><input class="form-control rule-days" type="number" min="1" step="1" placeholder="Tage"></div></div></div><input type="hidden" name="import_rules" id="import_rules"><button class="btn btn-sm btn-outline-secondary" type="button" onclick="addImportRule()">Weitere Regel</button><div class="form-text">Die spezifischste Regel gewinnt: Gerätenummer vor Gerät vor Raum vor globalem Fallback.</div></div>
    </form></details>
    <hr>
    <details class="mb-3"><summary><strong>Phoenix-Einweg-Sync (nur neue Geräte)</strong></summary>
    <h2 class="h6 mt-3">Phoenix-Einweg-Sync (nur neue Geräte)</h2>
    <p class="text-body-secondary">Lädt Prüfungen eines Phoenix-Kunden über die API und übernimmt ausschließlich Gerätenummern, die lokal noch nicht existieren. Der Bearer-Token wird nicht gespeichert.</p>
    <form method="post" class="row g-2">
      <input type="hidden" name="action" value="phoenix_sync">
      <div class="col-md-3"><label class="form-label" for="phoenix_customer_id">Phoenix-Kunden-ID</label><input class="form-control" id="phoenix_customer_id" name="phoenix_customer_id" inputmode="numeric" required></div>
      <div class="col-md-5"><label class="form-label" for="phoenix_token">Bearer-Token</label><input class="form-control" id="phoenix_token" name="phoenix_token" type="password" autocomplete="off" required></div>
      <div class="col-md-4"><label class="form-label" for="phoenix_api_url">API-URL</label><input class="form-control" id="phoenix_api_url" name="phoenix_api_url" value="https://api.phoenix-arbeitswelt.de/phoenix"></div>
      <div class="col-12"><button class="btn btn-outline-primary">Neue Phoenix-Geräte synchronisieren</button></div>
    </form></details>
    <?php if (is_array($stats) && !empty($stats['new_devices'])): ?><details class="mt-3"><summary>Neu angelegte Geräte (<?= count($stats['new_devices']) ?>)</summary><ul class="mt-2"><?php foreach ($stats['new_devices'] as $newDevice): ?><li><a href="<?= htmlspecialchars(url_for('geraete?device_id=' . (int) $newDevice['id']), ENT_QUOTES) ?>"><?= htmlspecialchars((string) $newDevice['number']) ?> · <?= htmlspecialchars((string) $newDevice['name']) ?></a></li><?php endforeach; ?></ul></details><?php endif; ?>
    <?php if (is_array($stats) && !empty($stats['updated_devices'])): ?><details class="mt-3"><summary>Aktualisierte Geräte (<?= count($stats['updated_devices']) ?>)</summary><ul class="mt-2"><?php foreach ($stats['updated_devices'] as $updatedDevice): ?><li><a href="<?= htmlspecialchars(url_for('geraete?device_id=' . (int) $updatedDevice['id']), ENT_QUOTES) ?>"><?= htmlspecialchars((string) $updatedDevice['number']) ?> · <?= htmlspecialchars((string) $updatedDevice['name']) ?></a></li><?php endforeach; ?></ul></details><?php endif; ?>
    <?php if (is_array($stats) && !empty($stats['not_imported'])): ?><details class="mt-3"><summary>Nicht importiert (<?= count($stats['not_imported']) ?>)</summary><div class="table-responsive mt-2"><table class="table table-sm"><thead><tr><th>Speicherplatz</th><th>Quelle</th><th>Grund</th></tr></thead><tbody><?php foreach ($stats['not_imported'] as $entry): ?><tr><td><?= htmlspecialchars((string) ($entry['storage_slot'] ?? '')) ?></td><td><?= htmlspecialchars((string) ($entry['source'] ?? '')) ?></td><td><?= htmlspecialchars((string) ($entry['reason'] ?? '')) ?></td></tr><?php endforeach; ?></tbody></table></div></details><?php endif; ?>
  </div>
</div>
<script>window.setNextAudit=function(days){document.getElementById('default_next_due_offset_days').value=days;};window.addImportRule=function(){const first=document.querySelector('.import-rule');const clone=first.cloneNode(true);clone.querySelectorAll('input').forEach(i=>i.value='');clone.querySelectorAll('select').forEach(s=>s.selectedIndex=0);document.getElementById('import-rules').appendChild(clone);};document.querySelectorAll('form[enctype="multipart/form-data"]').forEach(f=>f.addEventListener('submit',function(){const target=f.querySelector('#import_rules');if(!target)return;const rules=[];f.querySelectorAll('.import-rule').forEach(r=>rules.push({room:r.querySelector('.rule-room').value,device:r.querySelector('.rule-device').value,number:r.querySelector('.rule-number').value,inspection_type:r.querySelector('.rule-type').value,examiner:r.querySelector('.rule-examiner').value,next_due_offset_days:r.querySelector('.rule-days').value}));target.value=JSON.stringify(rules); }));</script>
<script>document.querySelectorAll('[data-import-date]').forEach(function(link){link.addEventListener('click',function(event){event.preventDefault();const field=document.querySelector('[name="default_test_date"]');const details=document.getElementById('pair-upload-panel');if(details)details.open=true;if(field)field.value=link.dataset.importDate;requestAnimationFrame(function(){document.getElementById('pair-upload')?.scrollIntoView({behavior:'smooth',block:'center'});if(field)field.focus({preventScroll:true});});});});</script>
<script>document.querySelectorAll('summary').forEach(function(summary){summary.childNodes.forEach(function(node){if(node.nodeType!==3)return;node.nodeValue=node.nodeValue.replace(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:[+-]\d{2}:?\d{2}|Z)/g,function(value){const date=new Date(value);return isNaN(date)?value:new Intl.DateTimeFormat('de-DE',{dateStyle:'short',timeStyle:'short'}).format(date);});});});</script>
<script>document.querySelectorAll('details').forEach(function(details){if(!details.querySelector('summary')?.textContent.includes('Nachbearbeitung aus Import'))return;details.querySelectorAll('li').forEach(function(item){const status=item.textContent.trim().split('·').pop().trim().toLowerCase();if(!status)return;const badge=document.createElement('span');badge.className='badge rounded-pill ms-1 '+(status==='bestanden'?'text-bg-success':(status==='durchgefallen'?'text-bg-danger':'text-bg-warning'));badge.textContent=status;item.lastChild.textContent='';item.appendChild(badge);});});</script>
<script>document.querySelectorAll('details').forEach(function(details){const summary=details.querySelector(':scope > summary');if(summary&&summary.textContent.trim().startsWith('Letzte Importe')){details.open=true;const latest=details.querySelector(':scope > div > details');if(latest)latest.open=true;}});</script>
<script>document.querySelectorAll('details').forEach(function(details){const summary=details.querySelector(':scope > summary');if(summary&&summary.textContent.trim().startsWith('Nachbearbeitung aus Import'))details.open=true;});</script>
<script>document.addEventListener('DOMContentLoaded',function(){const field=document.querySelector('form input[name="measurement_date"]');if(field&&field.type==='date'){field.required=false;field.closest('.col-md-4')?.style.setProperty('display','none');}});</script>
<script>document.addEventListener('DOMContentLoaded',function(){const form=document.querySelector('form[name="directory-import"], form[action=""]');const directory=document.getElementById('directory');const reports=document.getElementById('reports_directory');if(!directory||!reports)return;try{if(!directory.value)directory.value=localStorage.getItem('pruefapp-import-directory')||'';if(!reports.value)reports.value=localStorage.getItem('pruefapp-reports-directory')||'';}catch(_){}const save=()=>{try{localStorage.setItem('pruefapp-import-directory',directory.value);localStorage.setItem('pruefapp-reports-directory',reports.value);}catch(_){}};directory.form?.addEventListener('submit',save);reports.form?.addEventListener('submit',save);});</script>
<script>
(() => {
  const toggle = document.getElementById('import-auto-refresh');
  const panel = document.getElementById('inspection-import-panel');
  if (!toggle || !panel) return;
  const key = 'pruefapp-import-auto-refresh';
  try { toggle.checked = localStorage.getItem(key) === '1'; } catch (_) {}
  const restoreDetails = () => { const open = JSON.parse(sessionStorage.getItem('pruefapp-import-open-details') || '[]'); panel.querySelectorAll('details').forEach((node, index) => { if (open.includes(index)) node.open = true; }); };
  const saveDetails = () => { try { sessionStorage.setItem('pruefapp-import-open-details', JSON.stringify([...panel.querySelectorAll('details')].map((node, index) => node.open ? index : -1).filter(index => index >= 0))); } catch (_) {} };
  const enable = () => {
    try { localStorage.setItem(key, toggle.checked ? '1' : '0'); } catch (_) {}
    if (!toggle.checked) return;
    saveDetails();
    if (window.htmx) {
      panel.setAttribute('hx-get', window.location.href);
      panel.setAttribute('hx-trigger', 'every 30s');
      panel.setAttribute('hx-target', '#inspection-import-panel');
      panel.setAttribute('hx-select', '#inspection-import-panel');
      panel.setAttribute('hx-swap', 'outerHTML');
      window.htmx.process(panel);
    }
  };
  toggle.addEventListener('change', enable);
  document.body.addEventListener('htmx:beforeRequest', saveDetails);
  document.body.addEventListener('htmx:afterSwap', restoreDetails);
  restoreDetails();
  enable();
})();
</script>
<?php if (!empty($_GET['phoenix_job'])): ?><script>
(function(){const id=<?= json_encode((string)$_GET['phoenix_job']) ?>; const url=<?= json_encode(url_for('admin/pruefungen/import/'.rawurlencode((string)$_GET['phoenix_job']).'/status')) ?>; const poll=()=>fetch(url,{credentials:'same-origin'}).then(r=>r.json()).then(j=>{const row=document.querySelector('[data-phoenix-job="'+id+'"]');if(!row)return;row.querySelector('.job-state').textContent=j.state||'';row.querySelector('.job-progress').textContent=j.total?(j.step||0)+' / '+j.total:'—';row.querySelector('.job-device').textContent=j.current_device||'';const msg=row.querySelector('.job-message');if(msg)msg.textContent=j.message||j.error||'';if(j.state==='running'||j.state==='queued')setTimeout(poll,2000);});poll();})();
</script><?php endif; ?>
<script>document.querySelectorAll('[data-phoenix-job]').forEach(function(row){const id=row.dataset.phoenixJob;const state=row.querySelector('.job-state')?.textContent.trim();if(!id||!['done','error','cancelled'].includes(state))return;const cell=row.lastElementChild;if(!cell||cell.querySelector('[data-archive-job]'))return;const form=document.createElement('form');form.method='post';form.action='<?= htmlspecialchars(url_for('admin/pruefungen/import/'), ENT_QUOTES) ?>'+id+'/archivieren';form.className='mt-1';const button=document.createElement('button');button.type='submit';button.className='btn btn-sm btn-outline-secondary';button.dataset.archiveJob='1';button.textContent='Archivieren';button.addEventListener('click',function(event){if(button.dataset.confirmed!=='1'){event.preventDefault();button.dataset.confirmed='1';button.classList.remove('btn-outline-secondary');button.classList.add('btn-outline-danger');button.textContent='Wirklich archivieren?';}});form.appendChild(button);cell.appendChild(form);const details=row.querySelector('.job-details')?.parentElement;if(details&&!details.querySelector('[data-import-link]')){const link=document.createElement('a');link.href='<?= htmlspecialchars(url_for('admin/pruefungen/import?phoenix_job='), ENT_QUOTES) ?>'+encodeURIComponent(id);link.textContent='Import anzeigen';link.className='btn btn-sm btn-link p-0';link.dataset.importLink='1';details.appendChild(link);}});</script>
