<div class="card"><div class="card-body">
<h1 class="h4">Neue Prüfung</h1>
<p class="text-body-secondary">Gerät: <strong><?= htmlspecialchars((string) $device->external_number) ?> · <?= htmlspecialchars((string) $device->name) ?></strong></p>
<?php if (!empty($error)): ?><div class="alert alert-danger"><?= htmlspecialchars((string) $error) ?></div><?php endif; ?>
<form method="post" class="row g-3">
<div class="col-md-3"><label class="form-label">Prüfdatum</label><input class="form-control" type="date" name="test_date" value="<?= htmlspecialchars((string) $inspection->test_date) ?>" required><div class="form-text">Vorausgefüllt, bei Bedarf änderbar.</div></div>
<div class="col-md-9"><label class="form-label">Schutzklasse bestimmen</label><div class="row g-2" role="radiogroup"><?php foreach ([['I','Klasse I','Schuko-Stecker mit Schutzleiter (PE)','fa-plug-circle-check','SK I','⏚','Schuko','public/img/stecker/schuko.jpg'],['II','Klasse II','doppelte Isolierung, kein Schutzleiter','fa-shield-halved','SK II','▣','Eurostecker · Konturenstecker','public/img/stecker/euro-kontur-schuko.jpg'],['III','Klasse III','Kleinspannung ohne Netzanschluss','fa-battery-half','SK III','◇ III','Batterie · Kleinspannungsstecker','public/img/stecker/dc-hohlstecker.jpg'],['Kabel','Kabel','Kaltgeräte-/Verlängerungskabel','fa-link','SK Kabel','⌁','Kabel','']] as [$class, $title, $hint, $icon, $skLabel, $symbol, $plugLabel, $image]): ?><div class="col-6 col-xl-3"><label class="border rounded p-2 d-block h-100 protection-choice" data-sk="<?= htmlspecialchars($skLabel, ENT_QUOTES) ?>"><input class="visually-hidden" type="radio" name="protection_class" value="<?= $class ?>"<?= (string) $inspection->protection_class === $class ? ' checked' : '' ?>><span class="d-flex align-items-center justify-content-between mb-2"><span class="sk-symbol" aria-hidden="true"><?= htmlspecialchars($symbol) ?></span><span class="badge text-bg-dark"><?= htmlspecialchars($skLabel) ?></span></span><?php if ($image !== ''): ?><img class="img-fluid rounded mb-2 protection-plug-image" src="<?= htmlspecialchars(url_for($image), ENT_QUOTES) ?>" alt="Beispiel: <?= htmlspecialchars($plugLabel, ENT_QUOTES) ?>" loading="lazy"><?php endif; ?><i class="fa-solid <?= $icon ?> fs-3 d-block mb-1" aria-hidden="true"></i><strong><?= $title ?></strong><span class="d-block small text-body-secondary"><?= $hint ?></span><span class="badge rounded-pill text-bg-light border mt-2"><?= htmlspecialchars($plugLabel) ?></span></label></div><?php endforeach; ?></div><div class="form-text">Benning-SK-Zuordnung: echter Schuko-Stecker mit PE = SK I; Euro- oder Konturenstecker ohne sichtbare metallische Stiftkontakte = SK II; Kleinspannungsstecker/Batterie = SK III.</div></div>
<div class="col-md-6"><label class="form-label">Prüfart</label><input class="form-control" name="inspection_type" value="<?= htmlspecialchars((string) $inspection->inspection_type) ?>" readonly><div class="form-text">Wird automatisch aus der gewählten Schutzklasse abgeleitet. Durchführung durch eine prüfende Person unter Aufsicht der verantwortlichen Elektrofachkraft.</div></div>
<div class="col-md-6"><label class="form-label">Prüfer</label><?php if ($canChooseOtherExaminer): ?><select class="form-select" name="examiner" required><option value="">Bitte wählen</option><?php foreach ($users as $user): $label=trim((string) ($user->name ?? '')) . (trim((string) ($user->email ?? '')) !== '' ? ' · ' . $user->email : ''); $value=trim((string) ($user->email ?? $user->name ?? '')); ?><option value="<?= htmlspecialchars($value, ENT_QUOTES) ?>"<?= (string) $inspection->examiner === $value ? ' selected' : '' ?>><?= htmlspecialchars($label) ?></option><?php endforeach; ?></select><?php else: ?><input class="form-control" value="<?= htmlspecialchars((string) $inspection->examiner) ?>" readonly><input type="hidden" name="examiner" value="<?= htmlspecialchars((string) $inspection->examiner, ENT_QUOTES) ?>"><?php endif; ?></div>
<div class="col-md-3"><label class="form-label">Speicherplatz</label><input class="form-control" name="storage_slot" value="<?= htmlspecialchars((string) $inspection->storage_slot) ?>" placeholder="wird nach Messung eingetragen"></div>
<div class="col-md-6"><label class="form-label">Nächste Prüfung</label><div class="input-group"><input class="form-control next-date-suggestion" type="date" id="next_due_date" name="next_due_date" value="<?= htmlspecialchars((string) $inspection->next_due_date) ?>"><button class="btn btn-outline-success" type="button" id="confirm_next_due">Übernehmen</button></div><div class="btn-group btn-group-sm mt-2" role="group" aria-label="Prüfintervall"><button type="button" class="btn btn-outline-secondary interval-btn" data-days="182">½ Jahr</button><button type="button" class="btn btn-outline-secondary interval-btn" data-days="365">1 Jahr</button><button type="button" class="btn btn-outline-secondary interval-btn" data-days="730">2 Jahre</button></div><div class="form-text">Vorschlag: ein Jahr nach dem Prüfdatum. Gelb markiert, bis bestätigt.</div></div>
<div class="col-md-3"><label class="form-label">Erstunterweisung</label><input class="form-control" name="initial_instruction" value="<?= htmlspecialchars((string) ($inspection->initial_instruction ?? '')) ?>" placeholder="Datum oder Hinweis"></div><div class="col-md-3"><label class="form-label">Folgeunterweisung</label><input class="form-control" name="followup_instruction" value="<?= htmlspecialchars((string) ($inspection->followup_instruction ?? '')) ?>" placeholder="Datum oder Hinweis"></div>
<div class="col-12"><h2 class="h6">Sichtprüfung und Funktionsprüfung</h2><?php foreach (['label' => 'Beschriftung vollständig und lesbar', 'leitung' => 'Anschlussleitung und Zugentlastung ohne erkennbare Schäden', 'gehaeuse' => 'Gehäuse und Lüftungsöffnungen ohne erkennbare Schäden', 'stecker' => 'Stecker und Kontakte unbeschädigt', 'funktion' => 'Sicherheitsrelevante Funktionen arbeiten ordnungsgemäß'] as $key => $label): ?><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="checklist[<?= $key ?>]" value="ok"<?= (($inspection->checklist_json ?? '') !== '' && str_contains((string) $inspection->checklist_json, '"' . $key . '":"ok"')) ? ' checked' : '' ?>><label class="form-check-label"><?= htmlspecialchars($label) ?></label></div><?php endforeach; ?></div>
<div class="col-md-3"><label class="form-label">Regiezeit (Minuten)</label><input class="form-control" type="number" min="0" name="regie_minutes" value="<?= (int) ($inspection->regie_minutes ?? 0) ?>"></div>
<div class="col-md-9"><label class="form-label">Begründung Regiezeit</label><input class="form-control" name="regie_reason" value="<?= htmlspecialchars((string) ($inspection->regie_reason ?? '')) ?>"></div>
<div class="col-12 d-flex gap-2"><button class="btn btn-outline-primary" name="complete" value="0">Zwischenspeichern</button><button class="btn btn-primary" name="complete" value="1">Prüfung abschließen</button></div>
</form></div></div>
<style>.protection-choice{cursor:pointer;transition:border-color .15s,box-shadow .15s}.protection-choice:has(input:checked){border-color:var(--bs-primary)!important;box-shadow:0 0 0 .2rem rgba(var(--bs-primary-rgb),.2);background:rgba(var(--bs-primary-rgb),.04)}.sk-symbol{font:700 1.8rem/1 Arial,sans-serif;min-width:3rem;color:var(--bs-emphasis-color)}.protection-plug-image{width:100%;height:86px;object-fit:contain;background:#fff}</style>
<script>
(() => {
  const date = document.querySelector('[name="test_date"]');
  const next = document.getElementById('next_due_date');
  const type = document.querySelector('[name="inspection_type"]');
  const protection = [...document.querySelectorAll('[name="protection_class"]')];
  if (!date || !next) return;
  const update = days => { if (!date.value) return; const d = new Date(date.value + 'T12:00:00'); d.setDate(d.getDate() + Number(days)); next.value = d.toISOString().slice(0, 10); next.classList.add('bg-warning-subtle'); next.dataset.confirmed = '0'; };
  document.querySelectorAll('.interval-btn').forEach(button => button.addEventListener('click', () => update(button.dataset.days)));
  document.getElementById('confirm_next_due')?.addEventListener('click', () => { next.classList.remove('bg-warning-subtle'); next.dataset.confirmed = '1'; });
  date.addEventListener('change', () => update(365));
  const syncType = () => { const selected = protection.find(input => input.checked); if (selected && type) type.value = ({I:'Schutzklasse I', II:'Schutzklasse II', III:'Schutzklasse III', Kabel:'Kabelprüfung'})[selected.value] || ''; };
  protection.forEach(input => input.addEventListener('change', syncType)); syncType();
  if (next.value) next.classList.add('bg-warning-subtle');
})();
</script>
