<?php $scalar = static function ($value): string { if (is_array($value)) foreach (['brezel_name', 'name', 'email'] as $key) if (isset($value[$key]) && is_scalar($value[$key])) return (string) $value[$key]; return is_scalar($value) ? (string) $value : ''; }; ?>
<div class="card"><div class="card-body">
  <div class="d-flex justify-content-between align-items-start gap-3"><div><h1 class="h4 mb-1">Prüfung <?= htmlspecialchars((string) $inspection->external_number) ?></h1><div class="text-body-secondary"><a href="<?= htmlspecialchars(url_for('geraete?device_id=' . (int) $device->id), ENT_QUOTES) ?>"><?= htmlspecialchars((string) $device->external_number) ?> · <?= htmlspecialchars((string) $device->name) ?></a></div></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-secondary btn-sm" href="<?= htmlspecialchars(url_for('geraete?device_id=' . (int) $device->id), ENT_QUOTES) ?>">Zur Gerätehistorie</a><?php if ((string) $inspection->result_status === 'ausstehend' && current_user_has_role('admin')): ?><form method="post" action="<?= htmlspecialchars(url_for('admin/pruefungen/' . (int) $inspection->id . '/loeschen'), ENT_QUOTES) ?>" onsubmit="return confirm('Diese ausstehende Prüfung wirklich löschen?');"><button class="btn btn-outline-danger btn-sm" type="submit">Prüfung löschen</button></form><?php endif; ?></div></div>
  <dl class="row mt-4"><dt class="col-sm-3">Datum</dt><dd class="col-sm-9"><?= htmlspecialchars((string) ($inspection->test_date ?: '—')) ?></dd><dt class="col-sm-3">Prüfart</dt><dd class="col-sm-9"><?= htmlspecialchars((string) ($inspection->inspection_type ?: $scalar($raw['type'] ?? '—'))) ?></dd><dt class="col-sm-3">Prüfer</dt><dd class="col-sm-9"><?= htmlspecialchars((string) ($inspection->examiner ?: $scalar($raw['created_by'] ?? '—'))) ?></dd><dt class="col-sm-3">Nächste Prüfung</dt><dd class="col-sm-9"><?= htmlspecialchars((string) ($inspection->next_due_date ?: '—')) ?></dd><dt class="col-sm-3">Ergebnis</dt><dd class="col-sm-9"><?= htmlspecialchars((string) ($inspection->result_status ?: 'unbekannt')) ?></dd><dt class="col-sm-3">Raum</dt><dd class="col-sm-9"><?= htmlspecialchars((string) ($inspection->room_snapshot ?: '—')) ?></dd><dt class="col-sm-3">Quelle</dt><dd class="col-sm-9"><?= htmlspecialchars((string) ($inspection->source_file ?: $inspection->source_type ?: '—')) ?></dd></dl>
  <p class="small text-body-secondary">Speicherplatz dieser Prüfung: <?= htmlspecialchars((string) ($inspection->storage_slot ?: '—')) ?></p>
  <?php if (trim((string) ($inspection->report_path ?? '')) !== ''): ?><a class="btn btn-primary btn-sm mb-3" href="<?= htmlspecialchars(url_for('admin/pruefungen/' . (int) $inspection->id . '/bericht'), ENT_QUOTES) ?>" target="_blank" rel="noopener">Bericht als PDF öffnen</a><?php endif; ?>
  <?php if ($measurements): ?><h2 class="h6">Messwerte</h2><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Messung</th><th>Wert</th><th>Einheit</th><th>Ergebnis</th></tr></thead><tbody><?php foreach ($measurements as $measurement): ?><tr><td><?= htmlspecialchars($scalar($measurement['name'] ?? '')) ?></td><td><?= htmlspecialchars($scalar($measurement['value'] ?? '')) ?></td><td><?= htmlspecialchars($scalar($measurement['unit'] ?? '')) ?></td><td><?= htmlspecialchars($scalar($measurement['result'] ?? '')) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
  <?php if ($checklist): ?><h2 class="h6 mt-3">Prüfschritte</h2><div class="vstack gap-2"><?php foreach ($checklist as $step): ?><div class="border rounded p-2"><strong><?= htmlspecialchars($scalar($step['step'] ?? '')) ?></strong><?php if (!empty($step['criterion'])): ?><div class="small text-body-secondary"><?= htmlspecialchars($scalar($step['criterion'])) ?></div><?php endif; ?><?php if (array_key_exists('result', $step)): ?><div class="mt-1">Ergebnis: <?= htmlspecialchars($scalar($step['result'])) ?></div><?php endif; ?></div><?php endforeach; ?></div><?php endif; ?>
  <?php if (!$measurements && !$checklist): ?><p class="text-body-secondary">Für diese Prüfung wurden keine strukturierten Messwerte oder Prüfschritte gespeichert.</p><?php endif; ?>
</div></div>
