<section class="card shadow-sm" data-action-nav="Prüfarten & Befähigungen" data-action-icon="fa-clipboard-check">
  <div class="card-header"><strong><i class="fa-solid fa-clipboard-check me-2" aria-hidden="true"></i>Prüfarten &amp; Befähigungen</strong></div>
  <form method="post" class="card-body vstack gap-4">
    <p class="text-body-secondary mb-0">Aktive Anforderungen werden serverseitig beim Anlegen und Abschließen einer Prüfung geprüft. Nachweise werden im Benutzerprofil hinterlegt; Bestätigungen sind ausschließlich Superadmin-Aufgaben.</p>
    <?php foreach ($types as $type): $code = (string) $type['code']; ?>
      <section class="border rounded-3 p-3">
        <div class="d-flex flex-wrap justify-content-between align-items-center gap-3"><div><h2 class="h5 mb-1"><i class="fa-solid <?= htmlspecialchars((string) ($type['icon'] ?: 'fa-clipboard-check'), ENT_QUOTES) ?> me-2" aria-hidden="true"></i><?= htmlspecialchars((string) $type['name']) ?></h2><div class="small text-body-secondary">Geräte können mehrere Prüftypen besitzen; die Prüfdaten bleiben im jeweiligen Typ getrennt.</div></div><div class="d-flex align-items-end gap-3"><div><label class="form-label mb-1">Standardintervall (Tage)</label><input class="form-control" type="number" min="1" name="interval[<?= htmlspecialchars($code, ENT_QUOTES) ?>]" value="<?= (int) $type['default_interval_days'] ?>"></div><label class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="type_active[<?= htmlspecialchars($code, ENT_QUOTES) ?>]" value="1"<?= !empty($type['active']) ? ' checked' : '' ?>><span class="form-check-label">Prüfart aktiv</span></label></div></div>
        <?php if (!empty($byType[$code])): ?><div class="table-responsive mt-3"><table class="table table-sm align-middle mb-0"><thead><tr><th>Nachweis</th><th>Gültigkeit</th><th>Superadmin-Bestätigung</th><th>Aktiv</th></tr></thead><tbody><?php foreach ($byType[$code] as $requirement): $id = (int) $requirement['id']; ?><tr><td class="fw-semibold"><?= htmlspecialchars((string) $requirement['name']) ?></td><td><div class="input-group input-group-sm"><input class="form-control" type="number" min="0" name="validity_days[<?= $id ?>]" value="<?= (int) ($requirement['validity_days'] ?? 0) ?>"><span class="input-group-text">Tage (0 = unbegrenzt)</span></div></td><td><input class="form-check-input" type="checkbox" name="requires_confirmation[<?= $id ?>]" value="1"<?= !empty($requirement['requires_confirmation']) ? ' checked' : '' ?> aria-label="Bestätigung erforderlich"></td><td><input class="form-check-input" type="checkbox" name="requirement_active[<?= $id ?>]" value="1"<?= !empty($requirement['active']) ? ' checked' : '' ?> aria-label="Anforderung aktiv"></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
      </section>
    <?php endforeach; ?>
    <div><button class="btn btn-primary" type="submit"><i class="fa-solid fa-floppy-disk me-1" aria-hidden="true"></i>Konfiguration speichern</button></div>
  </form>
</section>
