<section class="card shadow-sm" id="companion-workspace-root">
  <div class="card-header fw-semibold"><i class="fa-solid fa-mobile-screen-button me-2" aria-hidden="true"></i>Companion verbunden</div>
  <div class="card-body">
    <div class="alert alert-success"><i class="fa-solid fa-link me-1" aria-hidden="true"></i>Dieses Smartphone ist für den aktuellen Arbeitstag mit deinem Prüfplatz verbunden.</div>
    <p class="text-body-secondary">Du kannst jetzt auf dem Computer Geräte anlegen oder eine Prüfung öffnen. Der Companion bleibt verbunden; Barcode- und Fotoerfassung werden dem gerade gewählten Gerät oder der Prüfung zugeordnet.</p>
    <section class="border rounded-3 p-3 mb-3"><h2 class="h6"><i class="fa-solid fa-barcode me-2" aria-hidden="true"></i>Barcode bereithalten</h2><p class="small text-body-secondary">Der Scan landet im gemeinsamen Eingang des Prüfplatzes und wird dort bewusst einem Feld zugeordnet.</p><div id="companion-workspace-result" class="mb-2"></div><div class="d-grid gap-2"><button id="companion-workspace-camera-scan" class="btn btn-primary" type="button"><i class="fa-solid fa-camera me-1" aria-hidden="true"></i>Barcode mit Kamera scannen</button><form hx-post="<?= htmlspecialchars(url_for('companion/' . $session['token'] . '/barcode-foto'), ENT_QUOTES) ?>" hx-target="#companion-workspace-result" hx-swap="innerHTML" hx-encoding="multipart/form-data" class="input-group"><input class="form-control" name="barcode_photo" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" required><button class="btn btn-secondary" type="submit"><i class="fa-solid fa-image me-1" aria-hidden="true"></i>Foto auswerten</button></form><form hx-post="<?= htmlspecialchars(url_for('companion/' . $session['token'] . '/barcode'), ENT_QUOTES) ?>" hx-target="#companion-workspace-result" hx-swap="innerHTML" class="input-group"><input class="form-control" name="barcode" placeholder="Barcode eingeben" autocomplete="off"><button class="btn btn-secondary" type="submit"><i class="fa-solid fa-check me-1" aria-hidden="true"></i>Senden</button></form></div><video id="companion-workspace-camera" class="w-100 rounded mt-3 d-none" playsinline></video></section>
    <section class="border rounded-3 p-3"><h2 class="h6"><i class="fa-solid fa-camera me-2" aria-hidden="true"></i>Foto an Prüfplatz senden</h2><form method="post" enctype="multipart/form-data" hx-post="<?= htmlspecialchars(url_for('companion/' . $session['token'] . '/fotos'), ENT_QUOTES) ?>" hx-target="#companion-workspace-result" hx-swap="innerHTML" hx-encoding="multipart/form-data" hx-indicator="#companion-workspace-photo-uploading" hx-disabled-elt="find button[type=submit]" class="vstack gap-2"><input class="form-control" name="photo" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" required><select class="form-select" name="media_type"><option value="type_plate">Typenschild</option><option value="condition">Zustand</option><option value="defect">Mangel</option><option value="disposal">Aussonderung</option><option value="other">Sonstiges</option></select><input class="form-control" name="caption" maxlength="1000" placeholder="Bemerkung (optional)"><button class="btn btn-primary" type="submit"><span id="companion-workspace-photo-uploading" class="spinner-border spinner-border-sm htmx-indicator me-1" aria-hidden="true"></span><i class="fa-solid fa-upload me-1" aria-hidden="true"></i>Foto übertragen</button></form></section>
  </div>
</section>
<script>(() => { const button = document.getElementById('companion-workspace-camera-scan'), video = document.getElementById('companion-workspace-camera'), result = document.getElementById('companion-workspace-result'); if (!button || button.dataset.bound) return; button.dataset.bound = '1'; let stream; button.addEventListener('click', async () => { if (!('BarcodeDetector' in window)) { result.innerHTML = '<div class="alert alert-info py-2 mb-0">Dieser Browser kann Barcodes nicht direkt mit der Kamera erkennen. Bitte „Foto auswerten“ verwenden oder den Code eingeben.</div>'; return; } try { stream = await navigator.mediaDevices.getUserMedia({video: {facingMode: {ideal: 'environment'}}}); video.srcObject = stream; video.classList.remove('d-none'); await video.play(); const detector = new BarcodeDetector({formats: ['code_128','code_39','ean_13','ean_8','qr_code']}); const scan = async () => { const hits = await detector.detect(video); if (hits[0]?.rawValue) { stream.getTracks().forEach(track => track.stop()); video.classList.add('d-none'); htmx.ajax('POST', '<?= htmlspecialchars(url_for('companion/' . $session['token'] . '/barcode'), ENT_QUOTES) ?>', {target: '#companion-workspace-result', swap: 'innerHTML', values: {barcode: hits[0].rawValue}}); return; } requestAnimationFrame(scan); }; scan(); } catch (_) { result.innerHTML = '<div class="alert alert-danger py-2 mb-0">Kamera konnte nicht geöffnet werden. Bitte die Kameraberechtigung prüfen.</div>'; } }); })();</script>
