<section class="card shadow-sm" id="companion-mobile-root">
  <div class="card-header"><strong><i class="fa-solid fa-mobile-screen-button me-2" aria-hidden="true"></i>Prüf-Companion</strong></div>
  <div class="card-body">
    <p class="mb-1"><strong><?= htmlspecialchars((string) $device->external_number) ?> · <?= htmlspecialchars((string) $device->name) ?></strong></p>
    <p class="small text-body-secondary">Prüfung <?= htmlspecialchars((string) $inspection->external_number) ?> · Übertragungen erscheinen direkt am verbundenen Prüfplatz.</p>
    <section class="border rounded-3 p-3 mb-3"><h2 class="h6"><i class="fa-solid fa-barcode me-2" aria-hidden="true"></i>Barcode scannen</h2><div id="companion-scan-result" class="mb-2"></div><div class="d-grid gap-2"><button id="companion-camera-scan" class="btn btn-primary" type="button"><i class="fa-solid fa-camera me-1" aria-hidden="true"></i>Kamera öffnen</button><form hx-post="<?= htmlspecialchars(url_for('companion/' . $session['token'] . '/barcode'), ENT_QUOTES) ?>" hx-target="#companion-scan-result" hx-swap="innerHTML" class="input-group"><input class="form-control" name="barcode" placeholder="Barcode manuell eingeben" autocomplete="off"><button class="btn btn-outline-secondary" type="submit">Senden</button></form></div><video id="companion-camera" class="w-100 rounded mt-3 d-none" playsinline></video></section>
    <section class="border rounded-3 p-3"><h2 class="h6"><i class="fa-solid fa-camera me-2" aria-hidden="true"></i>Foto aufnehmen</h2><div id="companion-photo-result" class="mb-2"></div><form hx-post="<?= htmlspecialchars(url_for('companion/' . $session['token'] . '/fotos'), ENT_QUOTES) ?>" hx-target="#companion-photo-result" hx-swap="innerHTML" hx-encoding="multipart/form-data" class="vstack gap-2"><input class="form-control" name="photo" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" required><select class="form-select" name="media_type"><option value="condition">Zustand</option><option value="defect">Mangel</option><option value="disposal">Aussonderung</option><option value="other">Sonstiges</option></select><input class="form-control" name="caption" maxlength="1000" placeholder="Bemerkung (optional)"><button class="btn btn-secondary" type="submit"><i class="fa-solid fa-upload me-1" aria-hidden="true"></i>Foto übertragen</button></form></section>
  </div>
</section>
<script>
(() => { const button = document.getElementById('companion-camera-scan'), video = document.getElementById('companion-camera'), result = document.getElementById('companion-scan-result'); if (!button || button.dataset.bound) return; button.dataset.bound = '1'; let stream; button.addEventListener('click', async () => { if (!('BarcodeDetector' in window)) { result.innerHTML = '<div class="alert alert-info py-2">Dein Browser unterstützt keinen Kamera-Barcode-Scan. Bitte den Code unten eingeben oder einen aktuellen mobilen Browser verwenden.</div>'; return; } try { stream = await navigator.mediaDevices.getUserMedia({video: {facingMode: {ideal: 'environment'}}}); video.srcObject = stream; video.classList.remove('d-none'); await video.play(); const detector = new BarcodeDetector({formats: ['code_128','code_39','ean_13','ean_8','qr_code']}); const scan = async () => { const hits = await detector.detect(video); if (hits[0]?.rawValue) { stream.getTracks().forEach(track => track.stop()); video.classList.add('d-none'); htmx.ajax('POST', '<?= htmlspecialchars(url_for('companion/' . $session['token'] . '/barcode'), ENT_QUOTES) ?>', {target: '#companion-scan-result', swap: 'innerHTML', values: {barcode: hits[0].rawValue}}); return; } requestAnimationFrame(scan); }; scan(); } catch (error) { result.innerHTML = '<div class="alert alert-danger py-2">Kamera konnte nicht geöffnet werden.</div>'; } }); })();
</script>
