<?php
$isConnected = ($session['state'] ?? '') === 'connected';
$pairUrl = !empty($session['token']) ? url_for('companion/' . $session['token']) : '';
$pairQrUrl = !empty($session['token']) ? url_for('companion/' . $session['token'] . '/qr') : '';
?>
<section class="card shadow-sm mb-3" id="inspection-companion-panel" data-action-nav="Prüf-Companion" data-action-icon="fa-mobile-screen-button"<?= $session !== [] ? ' hx-get="' . htmlspecialchars(url_for('admin/pruefungen/' . (int) $inspection->id . '/companion/status'), ENT_QUOTES) . '" hx-trigger="every 4s" hx-swap="outerHTML"' : '' ?>>
  <div class="card-header d-flex justify-content-between align-items-center gap-2 flex-wrap"><strong><i class="fa-solid fa-mobile-screen-button me-2" aria-hidden="true"></i>Prüf-Companion</strong><?php if ($session !== []): ?><span class="badge text-bg-<?= $isConnected ? 'success' : 'secondary' ?>"><i class="fa-solid <?= $isConnected ? 'fa-link' : 'fa-clock' ?> me-1" aria-hidden="true"></i><?= $isConnected ? 'Mobilgerät verbunden' : 'Warte auf Mobilgerät' ?></span><?php endif; ?></div>
  <div class="card-body">
    <?php if ($session === []): ?>
      <p class="text-body-secondary mb-3">Barcode-Scan und Kamera eines Smartphones für diese Prüfung verwenden. Nach dem einmaligen QR-Scan bleibt das Mobilgerät für die Arbeitsdauer sicher mit diesem Prüfplatz verbunden.</p>
      <form method="post" action="<?= htmlspecialchars(url_for('admin/pruefungen/' . (int) $inspection->id . '/companion'), ENT_QUOTES) ?>" hx-post="<?= htmlspecialchars(url_for('admin/pruefungen/' . (int) $inspection->id . '/companion'), ENT_QUOTES) ?>" hx-target="#inspection-companion-panel" hx-swap="outerHTML"><button class="btn btn-primary" type="submit"><i class="fa-solid fa-mobile-screen-button me-1" aria-hidden="true"></i>Mobilgerät verbinden</button></form>
    <?php else: ?>
      <p class="mb-2">Öffne diesen Kopplungslink einmal auf dem Mobilgerät. Er bleibt bis zu acht Stunden gültig; danach kann die Verbindung hier neu erzeugt oder jederzeit getrennt werden.</p>
      <div class="d-flex flex-wrap align-items-center gap-3 mb-3"><div class="bg-white border rounded p-2"><img src="<?= htmlspecialchars($pairQrUrl, ENT_QUOTES) ?>" width="176" height="176" alt="QR-Code zum Öffnen des Prüf-Companions"></div><div class="small text-body-secondary">Mit der Kamera-App oder einem QR-Scanner öffnen. Der QR-Code enthält nur den kurzlebigen Kopplungslink, keine Zugangsdaten.</div></div>
      <div class="input-group mb-2"><input id="companion-link" class="form-control font-monospace small" value="<?= htmlspecialchars($pairUrl, ENT_QUOTES) ?>" readonly><button class="btn btn-outline-secondary" type="button" data-copy-companion-link><i class="fa-solid fa-copy me-1" aria-hidden="true"></i>Kopieren</button><button class="btn btn-outline-secondary" type="button" data-share-companion-link><i class="fa-solid fa-share-nodes me-1" aria-hidden="true"></i>Teilen</button></div>
      <div class="small text-body-secondary mb-3"><i class="fa-solid fa-shield-halved me-1" aria-hidden="true"></i>Der Link ist ein temporärer, geschützter Arbeitszugang ohne Passwort. Bitte nicht weitergeben; die Berechtigung kann hier jederzeit getrennt werden.</div>
      <?php if (trim((string) ($session['latest_barcode'] ?? '')) !== ''): ?><div class="alert alert-info py-2"><i class="fa-solid fa-barcode me-1" aria-hidden="true"></i>Letzter Scan: <strong><?= htmlspecialchars((string) $session['latest_barcode']) ?></strong></div><?php endif; ?>
      <form method="post" action="<?= htmlspecialchars(url_for('admin/pruefungen/' . (int) $inspection->id . '/companion'), ENT_QUOTES) ?>" hx-post="<?= htmlspecialchars(url_for('admin/pruefungen/' . (int) $inspection->id . '/companion'), ENT_QUOTES) ?>" hx-target="#inspection-companion-panel" hx-swap="outerHTML"><input type="hidden" name="action" value="disconnect"><button class="btn btn-outline-danger btn-sm" type="submit"><i class="fa-solid fa-link-slash me-1" aria-hidden="true"></i>Verbindung trennen</button></form>
    <?php endif; ?>
  </div>
</section>
<script>(() => { document.querySelectorAll('[data-copy-companion-link]').forEach(button => { if (button.dataset.bound) return; button.dataset.bound = '1'; button.addEventListener('click', async () => { const input = document.getElementById('companion-link'); try { await navigator.clipboard.writeText(input.value); button.innerHTML = '<i class="fa-solid fa-check me-1" aria-hidden="true"></i>Kopiert'; } catch (_) { input.select(); document.execCommand('copy'); } }); }); document.querySelectorAll('[data-share-companion-link]').forEach(button => { if (button.dataset.bound) return; button.dataset.bound = '1'; button.addEventListener('click', async () => { const url = document.getElementById('companion-link')?.value || ''; if (navigator.share) { try { await navigator.share({title: 'Prüf-Companion', text: 'Mobilgerät für diese Prüfung verbinden', url}); } catch (_) {} } else { document.querySelector('[data-copy-companion-link]')?.click(); } }); }); })();</script>
