<section class="card shadow-sm" id="companion-workspace-root">
  <div class="card-header fw-semibold"><i class="fa-solid fa-mobile-screen-button me-2" aria-hidden="true"></i>Companion verbunden</div>
  <div class="card-body">
    <div class="alert alert-success"><i class="fa-solid fa-link me-1" aria-hidden="true"></i>Dieses Smartphone ist für den aktuellen Arbeitstag mit deinem Prüfplatz verbunden.</div>
    <p class="text-body-secondary">Du kannst jetzt auf dem Computer Geräte anlegen oder eine Prüfung öffnen. Der Companion bleibt verbunden; Barcode- und Fotoerfassung werden dem gerade gewählten Gerät oder der Prüfung zugeordnet.</p>
    <section class="border rounded-3 p-3 mb-3"><h2 class="h6"><i class="fa-solid fa-barcode me-2" aria-hidden="true"></i>Barcode bereithalten</h2><p class="small text-body-secondary">Der Scan landet im gemeinsamen Eingang des Prüfplatzes und wird dort bewusst einem Feld zugeordnet.</p><div id="companion-workspace-result" class="mb-2"></div><form hx-post="<?= htmlspecialchars(url_for('companion/' . $session['token'] . '/barcode-foto'), ENT_QUOTES) ?>" hx-target="#companion-workspace-result" hx-swap="innerHTML" hx-encoding="multipart/form-data" class="input-group mb-2"><input class="form-control" name="barcode_photo" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" required><button class="btn btn-secondary" type="submit"><i class="fa-solid fa-camera me-1" aria-hidden="true"></i>Foto auswerten</button></form><form hx-post="<?= htmlspecialchars(url_for('companion/' . $session['token'] . '/barcode'), ENT_QUOTES) ?>" hx-target="#companion-workspace-result" hx-swap="innerHTML" class="input-group"><input class="form-control" name="barcode" placeholder="Barcode eingeben" autocomplete="off"><button class="btn btn-primary" type="submit"><i class="fa-solid fa-check me-1" aria-hidden="true"></i>Senden</button></form></section>
    <section class="border rounded-3 p-3"><h2 class="h6"><i class="fa-solid fa-camera me-2" aria-hidden="true"></i>Foto an Prüfplatz senden</h2><form hx-post="<?= htmlspecialchars(url_for('companion/' . $session['token'] . '/fotos'), ENT_QUOTES) ?>" hx-target="#companion-workspace-result" hx-swap="innerHTML" hx-encoding="multipart/form-data" class="vstack gap-2"><input class="form-control" name="photo" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" required><select class="form-select" name="media_type"><option value="type_plate">Typenschild</option><option value="condition">Zustand</option><option value="defect">Mangel</option><option value="disposal">Aussonderung</option><option value="other">Sonstiges</option></select><input class="form-control" name="caption" maxlength="1000" placeholder="Bemerkung (optional)"><button class="btn btn-secondary" type="submit"><i class="fa-solid fa-upload me-1" aria-hidden="true"></i>Foto übertragen</button></form></section>
  </div>
</section>
