<div id="inspection-import-panel">
  <?php if (is_array($activeJob ?? null)): $activeState=(string)($activeJob['state'] ?? 'queued'); $activeRunning=in_array($activeState, ['queued','running','cancel_requested'], true); ?><div class="alert job-status-notice sticky-top <?= $activeRunning ? 'alert-primary' : ($activeState === 'done' ? 'alert-success' : 'alert-danger') ?> py-2 d-flex align-items-center gap-2" id="import-job-refresh" role="status" aria-live="polite" data-status-url="<?= htmlspecialchars(url_for('admin/pruefungen/import/' . rawurlencode((string) ($activeJob['id'] ?? '')) . '/status'), ENT_QUOTES) ?>" data-running="<?= $activeRunning ? '1' : '0' ?>"><span class="spinner-border spinner-border-sm<?= $activeRunning ? '' : ' d-none' ?>" aria-hidden="true"></span><span><strong><?= htmlspecialchars(BackgroundJobService::label((string) ($activeJob['type'] ?? 'background')), ENT_QUOTES) ?></strong> · <span class="job-progress"><?= (int) ($activeJob['step'] ?? 0) ?> / <?= (int) ($activeJob['total'] ?? 0) ?></span> · <span class="job-message"><?= htmlspecialchars((string) ($activeJob['message'] ?? ''), ENT_QUOTES) ?></span></span><?php if ($activeRunning): ?><small class="ms-auto text-nowrap" aria-live="polite">Aktualisierung in <span class="refresh-countdown">10</span>s</small><?php endif; ?></div><?php endif; ?>
  <div class="card">
    <div class="card-body">
    <div class="d-flex justify-content-between align-items-center gap-2 flex-wrap mb-2"><h1 class="h4 mb-0">Elektro-Prüfungen importieren</h1><a class="btn btn-sm btn-outline-secondary" href="<?= htmlspecialchars(url_for('admin/audit-log#audit-tasks-panel'), ENT_QUOTES) ?>"><i class="fa-solid fa-list-check me-1" aria-hidden="true"></i>Aufgaben &amp; Verlauf</a></div>
    <nav class="btn-toolbar gap-2 mb-3" aria-label="Zu Importformular springen"><div class="btn-group btn-group-sm" role="group"><a class="btn btn-primary" href="#directory-import"><i class="fa-solid fa-folder-open me-1" aria-hidden="true"></i>Verzeichnis</a><a class="btn btn-secondary" href="#pair-upload-panel"><i class="fa-solid fa-file-arrow-up me-1" aria-hidden="true"></i>CSV / ODS</a><a class="btn btn-secondary" href="#measurement-import"><i class="fa-solid fa-vial me-1" aria-hidden="true"></i>Messdaten</a><a class="btn btn-secondary" href="#phoenix-sync"><i class="fa-solid fa-cloud-arrow-down me-1" aria-hidden="true"></i>Phoenix</a><?php if (current_user_is_superadmin()): ?><a class="btn btn-warning" href="#report-regeneration"><i class="fa-solid fa-file-pdf me-1" aria-hidden="true"></i>Berichte</a><?php endif; ?></div></nav>
    <?php if (!empty($cron['healthy'])): ?><div class="alert alert-success py-2">Cron letzter Lauf: <?= htmlspecialchars((string) $cron['last_run']) ?></div><?php else: ?><div class="alert alert-warning py-2">Warnung: Der Phoenix-Cron wurde seit mehr als 5 Minuten nicht ausgeführt<?= !empty($cron['last_run']) ? ' (letzter Lauf: ' . htmlspecialchars((string) $cron['last_run']) . ')' : '' ?>.</div><?php endif; ?>
    <?php if (!empty($pendingMeasurementsByDate)): ?>
      <details class="mb-3" open>
        <summary><strong>Messdaten noch importieren</strong> (<?= array_sum(array_map('count', $pendingMeasurementsByDate)) ?> Prüfungen)</summary>
        <div class="small text-body-secondary mt-2">Für diese manuellen Prüfungen fehlen noch Messwerte. Nach dem Import werden die Prüfungen automatisch vervollständigt.</div>
        <?php $pendingDateIndex = 0; foreach ($pendingMeasurementsByDate as $pendingDate => $pendingRows): ?>
          <details class="border rounded mt-2"<?= $pendingDateIndex++ === 0 ? ' open' : '' ?>>
            <summary class="d-flex justify-content-between align-items-center gap-2 px-3 py-2"><span class="fw-semibold">Prüfdatum <?= htmlspecialchars(format_datetime_for_display((string) $pendingDate, 'd.m.Y'), ENT_QUOTES) ?></span><span class="badge text-bg-secondary"><?= count($pendingRows) ?></span></summary>
            <div class="px-3 pb-3">
              <div class="d-flex justify-content-end mt-2"><a class="btn btn-sm btn-outline-primary" href="#pair-upload" data-import-date="<?= htmlspecialchars((string) $pendingDate, ENT_QUOTES) ?>"><i class="fa-solid fa-file-arrow-up me-1" aria-hidden="true"></i>CSV/ODS für diesen Tag hochladen</a></div>
              <div class="table-responsive mt-2"><table class="table table-sm align-middle mb-0"><thead><tr><th>Prüfung</th><th>Gerät</th><th>Speicherplatz</th><th></th></tr></thead><tbody><?php foreach ($pendingRows as $pending): ?><tr><td><a href="<?= htmlspecialchars(url_for('admin/pruefungen/' . (int) $pending['inspection_id']), ENT_QUOTES) ?>"><?= htmlspecialchars((string) ($pending['inspection_number'] ?: '—')) ?></a></td><td><a href="<?= htmlspecialchars(url_for('geraete?device_id=' . (int) $pending['device_id']), ENT_QUOTES) ?>"><?= htmlspecialchars(trim((string) $pending['number'] . ' · ' . (string) $pending['name'])) ?></a></td><td><?= htmlspecialchars((string) ($pending['storage_slot'] ?: '—')) ?></td><td><a class="btn btn-sm btn-outline-primary" href="<?= htmlspecialchars(url_for('admin/pruefungen/' . (int) $pending['inspection_id'] . '/bearbeiten'), ENT_QUOTES) ?>">Prüfung öffnen</a></td></tr><?php endforeach; ?></tbody></table></div>
            </div>
          </details>
        <?php endforeach; ?>
      </details>
    <?php endif; ?>
    <?php if (!empty($importLogs)): ?><details class="mb-3"><summary><strong>Letzte Importe</strong> (<?= count($importLogs) ?>)</summary><div class="mt-2"><?php foreach ($importLogs as $log): $logStats=$log['stats']??[]; ?><details class="border rounded p-2 mb-2"><summary><?= htmlspecialchars((string) ($log['type'] ?? 'Import')) ?> · <?= htmlspecialchars((string) ($log['created_at'] ?? '')) ?> · <?= (int) ($logStats['imported'] ?? 0) ?> Prüfungen</summary><div class="small mt-2">Neu: <?= (int) ($logStats['devices'] ?? 0) ?> Geräte · Aktualisiert: <?= (int) ($logStats['updated'] ?? 0) ?> Prüfungen · Übersprungen: <?= (int) ($logStats['skipped'] ?? 0) ?></div><?php foreach (['new_devices' => 'Neue Geräte', 'updated_devices' => 'Aktualisierte Geräte'] as $listKey => $listLabel): if (!empty($logStats[$listKey])): ?><div class="small mt-2"><strong><?= $listLabel ?>:</strong> <?php foreach ($logStats[$listKey] as $device): ?><a class="me-2" href="<?= htmlspecialchars(url_for('geraete?device_id=' . (int) $device['id']), ENT_QUOTES) ?>"><?= htmlspecialchars((string) ($device['number'] ?? '')) ?></a><?php endforeach; ?></div><?php endif; endforeach; ?><details class="mt-2"><summary>Debug-Log anzeigen</summary><pre class="small mb-0 mt-2"><?= htmlspecialchars((string) json_encode($logStats, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)) ?></pre></details></details><?php endforeach; ?></div></details><?php endif; ?>
    <details class="mb-3" id="measurement-import" data-action-nav="Messdaten" data-action-icon="fa-vial"><summary><strong><i class="fa-solid fa-file-csv me-1" aria-hidden="true"></i>Messdaten zu Prüfweb-Prüfungen importieren</strong></summary><form method="post" enctype="multipart/form-data" class="row g-2 mt-2"><input type="hidden" name="action" value="pending_measurement_import"><div class="col-md-4"><label class="form-label">Prüfdatum</label><input class="form-control" type="date" name="measurement_date" required></div><div class="col-md-5"><label class="form-label">Messdaten (CSV)</label><input class="form-control" type="file" name="measurement_csv" accept=".csv" required></div><div class="col-md-3 d-flex align-items-end"><button class="btn btn-primary w-100"><i class="fa-solid fa-clock me-1" aria-hidden="true"></i>Im Hintergrund importieren</button></div><div class="col-12 form-text">Es werden ausschließlich in Prüfweb angelegte Prüfungen mit exakt gleichem Prüfdatum und Speicherplatz ergänzt. Nicht passende CSV-Zeilen bleiben unverändert und werden als übersprungen protokolliert.</div></form></details>
    <?php foreach (($importLogs ?? []) as $historyLog): $historyStats = $historyLog['stats'] ?? []; if (empty($historyStats['updated_inspections'])) continue; ?><details class="mb-3"><summary><i class="fa-solid fa-clock-rotate-left me-1" aria-hidden="true"></i>Nachbearbeitung aus Import vom <?= htmlspecialchars((string) ($historyLog['created_at'] ?? ''), ENT_QUOTES) ?></summary><div class="table-responsive mt-2"><table class="table table-sm align-middle mb-0"><thead><tr><th>Prüfung</th><th>Gerät</th><th>Speicherplatz</th><th>Ergebnis</th></tr></thead><tbody><?php foreach ($historyStats['updated_inspections'] as $historyInspection): $historyStatus = InspectionEvaluationService::presentation((string) ($historyInspection['status'] ?? '')); $isSlot = !empty($historyInspection['number_is_storage_slot']); ?><tr><td><a href="<?= htmlspecialchars(url_for('admin/pruefungen/' . (int) ($historyInspection['id'] ?? 0)), ENT_QUOTES) ?>"><?= htmlspecialchars($isSlot ? 'Prüfung öffnen' : (string) ($historyInspection['number'] ?? 'Prüfung')) ?></a><?= $isSlot ? '<div class="small text-body-secondary">Prüfnummer im Import fehlt</div>' : '' ?></td><td><?= htmlspecialchars(trim((string) ($historyInspection['device_number'] ?? '') . ' · ' . (string) ($historyInspection['device_name'] ?? '')) ?: '—') ?></td><td><?= htmlspecialchars((string) ($historyInspection['storage_slot'] ?? '—')) ?></td><td><span class="badge text-bg-<?= htmlspecialchars($historyStatus['class'], ENT_QUOTES) ?>"><i class="fa-solid <?= htmlspecialchars($historyStatus['icon'], ENT_QUOTES) ?> me-1" aria-hidden="true"></i><?= htmlspecialchars($historyStatus['label']) ?></span></td></tr><?php endforeach; ?></tbody></table></div></details><?php endforeach; ?>
    <p class="text-body-secondary">Importe aus JSON/JSONL, CSV (ODS optional) und Phoenix laufen im Hintergrund. Fortschritt, Abschluss und Fehler stehen unter <a href="<?= htmlspecialchars(url_for('admin/audit-log#audit-tasks-panel'), ENT_QUOTES) ?>">Aufgaben &amp; Verlauf</a> sowie in den Benachrichtigungen.</p>
    <?php if (is_array($stats)): ?><div class="row g-2 mb-3"><?php foreach (['files' => 'Dateien', 'imported' => 'Prüfungen neu', 'updated' => 'Prüfungen aktualisiert', 'devices' => 'Geräte neu', 'reports' => 'Berichte', 'skipped' => 'Übersprungen'] as $key => $label): ?><div class="col-6 col-md-2"><div class="border rounded p-2 text-center"><div class="small text-body-secondary"><?= $label ?></div><strong><?= (int) ($stats[$key] ?? 0) ?></strong></div></div><?php endforeach; ?></div><details class="mb-3"><summary>Debug-Output anzeigen</summary><pre class="small mt-2"><?= htmlspecialchars((string) json_encode($stats, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)) ?></pre></details><?php endif; ?>
    <?php if (current_user_is_superadmin()): ?><details class="card border-danger mb-3" id="legacy-import-rebuild" data-action-nav="Quellen-Neuaufbau" data-action-icon="fa-triangle-exclamation"><summary class="card-header fw-semibold text-danger"><i class="fa-solid fa-arrows-rotate me-1" aria-hidden="true"></i>Importbestand aus kuratierten Quellen neu aufbauen</summary><div class="card-body"><p class="small text-body-secondary">Erstellt zuerst ein geprüftes Datenbank-Backup, entfernt ausschließlich JSON-/CSV-Importprüfungen und setzt Rechnungsdaten zurück. Anschließend läuft der normale, fortsetzbare Verzeichnisimport. Prüfweb-Prüfungen bleiben erhalten.</p><form method="post" class="row g-2"><input type="hidden" name="action" value="import_rebuild_preview"><div class="col-md-9"><label class="form-label" for="rebuild_directory">Kuratiertes Quellenverzeichnis</label><input class="form-control" id="rebuild_directory" name="rebuild_directory" required value="<?= htmlspecialchars((string) ($_POST['rebuild_directory'] ?? ''), ENT_QUOTES) ?>" placeholder="Serverpfad mit JSON/JSONL und vollständigen CSV/ODS-Paaren"></div><div class="col-md-3 d-flex align-items-end"><button class="btn btn-outline-danger w-100"><i class="fa-solid fa-magnifying-glass me-1" aria-hidden="true"></i>Vorschau prüfen</button></div></form><?php if (is_array($rebuildPreview ?? null)): $rebuildAudit=$rebuildPreview['audit']; $rebuildReset=$rebuildPreview['reset']; ?><div class="alert alert-warning mt-3 mb-2"><strong>Vorschau:</strong> <?= (int) ($rebuildReset['imported_inspections'] ?? 0) ?> Importprüfungen und <?= (int) ($rebuildReset['billing_invoices_to_reset'] ?? 0) ?> Rechnungen werden zurückgesetzt. Quellen: <?= (int) ($rebuildAudit['json']['records'] ?? 0) ?> JSON, <?= (int) ($rebuildAudit['jsonl']['records'] ?? 0) ?> JSONL, <?= (int) ($rebuildAudit['csv_ods']['pairs'] ?? 0) ?> CSV/ODS-Paare.</div><?php if (($rebuildAudit['csv_ods']['unpaired_csv'] ?? []) !== []): ?><div class="alert alert-danger">Nicht startbar: <?= count($rebuildAudit['csv_ods']['unpaired_csv']) ?> CSV-Datei(en) ohne passende ODS.</div><?php else: ?><form method="post" class="row g-2 mt-1"><input type="hidden" name="action" value="import_rebuild_start"><input type="hidden" name="rebuild_directory" value="<?= htmlspecialchars((string) $rebuildPreview['directory'], ENT_QUOTES) ?>"><div class="col-md-8"><label class="form-label">Bestätigung</label><input class="form-control" name="rebuild_confirmation" required placeholder="IMPORT NEU AUFBAUEN"></div><div class="col-md-4 d-flex align-items-end"><button class="btn btn-danger w-100"><i class="fa-solid fa-database me-1" aria-hidden="true"></i>Backup, Reset &amp; Import starten</button></div></form><?php endif; ?><?php endif; ?></div></details><?php endif; ?>
    <?php if (current_user_is_superadmin()): ?>
      <style>#legacy-import-rebuild{display:none!important}</style>
      <details class="card border-danger mb-3" id="import-rebuild" open>
        <summary class="card-header fw-semibold text-danger"><i class="fa-solid fa-table-list me-1" aria-hidden="true"></i>Importbestand als Kandidaten neu aufbauen</summary>
        <div class="card-body">
          <p class="small text-body-secondary">Erstellt zuerst ein geprüftes Backup, behält ausschließlich direkt in Prüfweb angelegte Prüfungen und leert historische Import- sowie Rechnungsdaten. Danach werden Quellen erst als Kandidaten erfasst; nur konfliktfreie Gruppen werden automatisch importiert. Einzelne Mess-CSV ohne ODS werden dabei nicht als historische Quelle verarbeitet.</p>
          <form method="post" class="row g-2"><input type="hidden" name="action" value="import_candidate_start"><div class="col-md-7"><label class="form-label" for="candidate_directory">Kuratiertes Quellenverzeichnis</label><input class="form-control" id="candidate_directory" name="rebuild_directory" required placeholder="Serverpfad mit JSON/JSONL und vollständigen CSV/ODS-Paaren"></div><div class="col-md-3"><label class="form-label" for="candidate_confirmation">Bestätigung</label><input class="form-control" id="candidate_confirmation" name="rebuild_confirmation" required placeholder="KANDIDATEN NEU AUFBAUEN"></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-danger w-100"><i class="fa-solid fa-play me-1" aria-hidden="true"></i>Starten</button></div></form>
          <?php if (!empty($candidateRebuildRunning)): ?><div class="alert alert-primary mt-3 mb-0"><span class="spinner-border spinner-border-sm me-2" aria-hidden="true"></span>Der Kandidatenlauf verarbeitet noch Quellen. Die offenen Fälle werden erst nach Abschluss geladen.</div><?php elseif (($candidateGroups ?? []) !== []): ?>
            <hr><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-2"><p class="mb-0"><strong>Kandidatenlauf #<?= (int) ($candidateRunId ?? 0) ?></strong> · offene Fälle bitte je Feld entscheiden.</p><button type="button" class="btn btn-sm btn-outline-secondary" id="candidate-toggle-all" aria-expanded="false"><i class="fa-solid fa-angles-down me-1" aria-hidden="true"></i>Alle aufklappen</button></div>
            <?php foreach ($candidateGroups as $candidateGroup): ?>
              <?php if (($candidateGroup['state'] ?? '') === 'accepted' || ($candidateGroup['state'] ?? '') === 'resolved') continue; ?>
              <?php $conflictFields = array_keys((array) ($candidateGroup['conflicts'] ?? [])); $fieldLabels = ['inspection_number' => 'Prüfungsnummer', 'device_number' => 'Gerätenummer', 'test_date' => 'Prüfdatum', 'inspection_type' => 'Prüfart', 'room_snapshot' => 'Raum', 'regie_minutes' => 'Regie', 'result_status' => 'Ergebnis', 'manufacturer' => 'Hersteller', 'device_model' => 'Modell', 'storage_slot' => 'Speicherplatz']; $cellClass = static fn(string $field): string => in_array($field, $conflictFields, true) ? ' class="table-warning"' : ''; ?>
              <details class="border rounded p-2 mb-2 <?= $conflictFields !== [] ? 'border-warning' : '' ?>"><summary><span class="badge text-bg-<?= ($candidateGroup['state'] ?? '') === 'number_missing' ? 'warning text-dark' : 'danger' ?> me-1"><?= htmlspecialchars((string) ($candidateGroup['state'] ?? 'offen')) ?></span><?= (int) ($candidateGroup['source_count'] ?? 0) ?> Quellen · <?= htmlspecialchars(substr((string) ($candidateGroup['group_key'] ?? ''), 0, 12)) ?><?php if ($conflictFields !== []): ?> <span class="badge text-bg-warning text-dark ms-1"><i class="fa-solid fa-triangle-exclamation me-1" aria-hidden="true"></i><?= count($conflictFields) ?> Widerspruch<?= count($conflictFields) === 1 ? '' : 'e' ?></span><?php endif; ?></summary>
                <form method="post" class="mt-2"><input type="hidden" name="action" value="import_candidate_decide"><input type="hidden" name="candidate_run_id" value="<?= (int) ($candidateRunId ?? 0) ?>"><input type="hidden" name="group_key" value="<?= htmlspecialchars((string) ($candidateGroup['group_key'] ?? ''), ENT_QUOTES) ?>">
                  <?php if ($conflictFields !== []): ?><div class="alert alert-warning py-2 small"><i class="fa-solid fa-triangle-exclamation me-1" aria-hidden="true"></i><strong>Widersprüchliche Felder:</strong> <?= htmlspecialchars(implode(', ', array_map(static fn(string $field): string => $fieldLabels[$field] ?? $field, $conflictFields))) ?>. Die gelb markierten Tabellenzellen bitte unten entscheiden.</div><?php elseif (($candidateGroup['state'] ?? '') === 'review'): ?><div class="alert alert-warning py-2 small"><i class="fa-solid fa-circle-question me-1" aria-hidden="true"></i>Die Zuordnung ist nicht eindeutig; es gibt aber keinen Feldwert-Widerspruch.</div><?php endif; ?>
                  <div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Quelle</th><th>Prüfung</th><th>Gerät</th><th>Speicherplatz</th><th>Datum</th><th>Art</th><th>Raum</th><th>Regie</th><th>Ergebnis</th></tr></thead><tbody><?php foreach (($candidateGroup['candidates'] ?? []) as $candidate): $raw = json_decode((string) ($candidate['raw_json'] ?? '{}'), true) ?: []; ?><tr><td><?= htmlspecialchars((string) ($candidate['source_kind'] ?? '')) ?><div class="small text-body-secondary text-break font-monospace"><?= htmlspecialchars((string) ($candidate['source_path'] ?? '')) ?><?= (int) ($candidate['source_row_no'] ?? 0) > 0 ? ':' . (int) $candidate['source_row_no'] : '' ?></div></td><td<?= $cellClass('inspection_number') ?>><?= htmlspecialchars((string) ($candidate['inspection_number'] ?? '—')) ?></td><td<?= $cellClass('device_number') ?>><?= htmlspecialchars((string) ($candidate['device_number'] ?? '—')) ?></td><td<?= $cellClass('storage_slot') ?>><?= htmlspecialchars((string) ($candidate['storage_slot'] ?? '—')) ?></td><td<?= $cellClass('test_date') ?>><?= htmlspecialchars((string) ($candidate['test_date'] ?? '—')) ?></td><td<?= $cellClass('inspection_type') ?>><?= htmlspecialchars((string) ($candidate['inspection_type'] ?? '—')) ?></td><td<?= $cellClass('room_snapshot') ?>><?= htmlspecialchars((string) ($raw['room_snapshot'] ?? $raw['room'] ?? '—')) ?></td><td<?= $cellClass('regie_minutes') ?>><?= htmlspecialchars((string) ($raw['regie_minutes'] ?? '—')) ?></td><td<?= $cellClass('result_status') ?>><?= htmlspecialchars((string) ($raw['result_status'] ?? '—')) ?></td></tr><?php endforeach; ?></tbody></table></div>
                  <?php if (($candidateGroup['state'] ?? '') === 'number_missing'): ?><div class="row g-2 mb-2"><div class="col-md-3"><label class="form-label">Prüfungsnummer</label><input class="form-control form-control-sm" name="field_source[__inspection_number]" required></div><div class="col-md-3"><label class="form-label">Gerätenummer</label><input class="form-control form-control-sm" name="field_source[__device_number]" required></div><div class="col-md-3"><label class="form-label">Prüfdatum</label><input class="form-control form-control-sm" type="date" name="field_source[__test_date]" required></div><div class="col-md-3"><label class="form-label">Prüfart</label><input class="form-control form-control-sm" name="field_source[__inspection_type]" placeholder="SK1" required></div></div><?php endif; ?>
                  <?php if (($candidateGroup['state'] ?? '') === 'number_missing'): ?><details class="mb-2"><summary class="small text-body-secondary"><i class="fa-solid fa-code me-1" aria-hidden="true"></i>Vollständige Quelldaten der Zeile anzeigen</summary><div class="mt-2"><?php foreach (($candidateGroup['candidates'] ?? []) as $candidate): $candidateRaw = json_decode((string) ($candidate['raw_json'] ?? '{}'), true) ?: []; ?><div class="small fw-semibold font-monospace"><?= htmlspecialchars((string) ($candidate['source_path'] ?? '')) ?><?= (int) ($candidate['source_row_no'] ?? 0) > 0 ? ':' . (int) $candidate['source_row_no'] : '' ?></div><pre class="small border rounded bg-body-tertiary p-2 text-break text-wrap"><?= htmlspecialchars((string) json_encode($candidateRaw, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)) ?></pre><?php endforeach; ?></div></details><?php endif; ?>
                  <?php foreach (($candidateGroup['conflicts'] ?? []) as $field => $values): ?><div class="row g-2 mb-2"><label class="col-md-3 col-form-label">Wert für <?= htmlspecialchars((string) $field) ?></label><div class="col-md-9"><select class="form-select form-select-sm" name="field_source[<?= htmlspecialchars((string) $field, ENT_QUOTES) ?>]"><option value="">Bitte auswählen</option><?php foreach (($candidateGroup['candidates'] ?? []) as $candidate): $candidateRaw = json_decode((string) ($candidate['raw_json'] ?? '{}'), true) ?: []; $candidateValue = $candidate[$field] ?? ($candidateRaw[$field] ?? ''); if ((string) $candidateValue === '') continue; ?><option value="<?= (int) ($candidate['id'] ?? 0) ?>"><?= htmlspecialchars((string) ($candidate['source_kind'] ?? '') . ' · ' . (string) $candidateValue) ?></option><?php endforeach; ?></select></div></div><?php endforeach; ?>
                  <div class="d-flex flex-wrap gap-2"><button class="btn btn-primary btn-sm" name="decision" value="merge"><i class="fa-solid fa-code-merge me-1" aria-hidden="true"></i>Feldweise zusammenführen</button><button class="btn btn-secondary btn-sm" name="decision" value="separate">Getrennt importieren</button><button class="btn btn-outline-danger btn-sm" name="decision" value="discard">Verwerfen</button></div>
                </form>
              </details>
            <?php endforeach; ?>
          <?php endif; ?>
        </div>
      </details>
    <?php endif; ?>
    <?php if ($message !== null): ?><div class="alert alert-info"><?= htmlspecialchars($message) ?></div><?php endif; ?>
    <form method="post" class="row g-2" id="directory-import" data-action-nav="Verzeichnisimport" data-action-icon="fa-folder-open" name="directory-import">
      <input type="hidden" name="action" value="directory_import_job">
      <div class="col-md-6"><label class="form-label" for="directory">Importverzeichnis</label><input class="form-control" id="directory" name="directory" required placeholder="/tmp/berichte"><div class="form-text">JSON/JSONL oder CSV; eine ODS ergänzt Gerätedaten, ist aber nicht erforderlich.</div></div><div class="col-md-6"><label class="form-label" for="reports_directory">PDF-Quellverzeichnis (optional)</label><input class="form-control" id="reports_directory" name="reports_directory" placeholder="/tmp/berichte"><div class="form-text">Kann derselbe Ordner sein. PDFs werden über die führende Prüfnummer zugeordnet.</div></div>
      <div class="col-md-4"><label class="form-label" for="directory_default_inspection_type">Prüfart für fehlende Angaben</label><input class="form-control" id="directory_default_inspection_type" name="default_inspection_type" placeholder="z. B. Wiederholungsprüfung SK1"></div>
      <div class="col-md-4"><label class="form-label" for="directory_default_examiner">Prüfer für fehlende Angaben</label><select class="form-select" id="directory_default_examiner" name="default_examiner"><option value="">Bitte wählen</option><?php foreach (($examinerUsers ?? []) as $examinerUser): ?><option value="<?= htmlspecialchars((string) $examinerUser['value'], ENT_QUOTES) ?>"><?= htmlspecialchars((string) $examinerUser['label']) ?></option><?php endforeach; ?></select></div>
      <div class="col-md-4"><label class="form-label" for="directory_default_next_due_offset_days">Tage bis zur nächsten Prüfung</label><div class="input-group"><input class="form-control" id="directory_default_next_due_offset_days" name="default_next_due_offset_days" type="number" min="1" step="1" placeholder="z. B. 365"><button class="btn btn-outline-secondary" type="button" onclick="document.getElementById('directory_default_next_due_offset_days').value=365">365</button><button class="btn btn-outline-secondary" type="button" onclick="document.getElementById('directory_default_next_due_offset_days').value=730">730</button></div><div class="form-text">Wird relativ zum jeweiligen Prüfdatum berechnet.</div></div>
      <div class="col-12"><button class="btn btn-primary"><i class="fa-solid fa-clock me-1" aria-hidden="true"></i>Im Hintergrund importieren</button></div>
    </form>
    <details class="mb-3" id="pair-upload-panel" data-action-nav="CSV / ODS" data-action-icon="fa-file-arrow-up"><summary><strong>Aktuelle Prüfung als Dateien hochladen</strong></summary>
    <h2 class="h6 mt-3">Aktuelle Prüfung als Paar hochladen</h2>
    <p class="text-body-secondary">ODS ist optional; ohne ODS werden Messdaten anhand von Prüfdatum und Speicherplatz einer vorhandenen Prüfung zugeordnet.</p>
    <form method="post" enctype="multipart/form-data" class="row g-2" id="pair-upload">
      <div class="col-md-6"><label class="form-label" for="csv">Messdaten (CSV)</label><input class="form-control" id="csv" name="csv" type="file" accept=".csv" required></div>
      <div class="col-md-6"><label class="form-label" for="ods">Gerätedaten (ODS, optional)</label><input class="form-control" id="ods" name="ods" type="file" accept=".ods"></div>
      <div class="col-md-4"><label class="form-label" for="default_inspection_type">Prüfart für fehlende Angaben</label><input class="form-control" id="default_inspection_type" name="default_inspection_type" placeholder="z. B. Wiederholungsprüfung SK1"></div>
      <div class="col-md-4"><label class="form-label" for="default_examiner">Prüfer für fehlende Angaben</label><select class="form-select" id="default_examiner" name="default_examiner"><option value="">Bitte wählen</option><?php foreach (($examinerUsers ?? []) as $examinerUser): ?><option value="<?= htmlspecialchars((string) $examinerUser['value'], ENT_QUOTES) ?>"><?= htmlspecialchars((string) $examinerUser['label']) ?></option><?php endforeach; ?></select></div>
      <div class="col-md-4"><label class="form-label" for="default_next_due_offset_days">Tage bis zur nächsten Prüfung</label><div class="input-group"><input class="form-control" id="default_next_due_offset_days" name="default_next_due_offset_days" type="number" min="1" step="1" placeholder="z. B. 365"><button class="btn btn-outline-secondary" type="button" onclick="setNextAudit(365)">365 Tage</button><button class="btn btn-outline-secondary" type="button" onclick="setNextAudit(730)">730 Tage</button></div><div class="form-text">Wird relativ zum jeweiligen Prüfdatum berechnet.</div></div>
      <div class="col-md-4"><label class="form-label" for="default_test_date">Prüfdatum der Messdaten (optional)</label><input class="form-control" id="default_test_date" name="default_test_date" type="date"><div class="form-text">Überschreibt das Datum aus der Datei, wenn gesetzt.</div></div>
      <div class="col-12"><button class="btn btn-primary"><i class="fa-solid fa-clock me-1" aria-hidden="true"></i>Paar im Hintergrund importieren</button></div>
      <div class="col-12 mt-3"><label class="form-label">Regeln für Raum/Gerät</label><div id="import-rules"><div class="row g-2 import-rule mb-2"><div class="col-md-2"><input class="form-control rule-room" placeholder="Raum, z. B. K203"></div><div class="col-md-2"><input class="form-control rule-device" placeholder="Gerät/Bezeichnung"></div><div class="col-md-2"><input class="form-control rule-number" placeholder="Gerätenummer (optional)"></div><div class="col-md-2"><input class="form-control rule-type" placeholder="Prüfart"></div><div class="col-md-2"><select class="form-select rule-examiner"><option value="">Prüfer</option><?php foreach (($examinerUsers ?? []) as $examinerUser): ?><option value="<?= htmlspecialchars((string) $examinerUser['value'], ENT_QUOTES) ?>"><?= htmlspecialchars((string) $examinerUser['label']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><input class="form-control rule-days" type="number" min="1" step="1" placeholder="Tage"></div></div></div><input type="hidden" name="import_rules" id="import_rules"><button class="btn btn-sm btn-outline-secondary" type="button" onclick="addImportRule()">Weitere Regel</button><div class="form-text">Die spezifischste Regel gewinnt: Gerätenummer vor Gerät vor Raum vor globalem Fallback.</div></div>
    </form></details>
    <hr>
    <details class="mb-3" id="phoenix-sync" data-action-nav="Phoenix-Sync" data-action-icon="fa-cloud-arrow-down"><summary><strong>Phoenix synchronisieren</strong></summary>
    <h2 class="h6 mt-3">Phoenix synchronisieren</h2>
    <p class="text-body-secondary">Der Zugang wird zentral unter <a href="<?= htmlspecialchars(url_for('admin/konfiguration#settings-phoenix-panel'), ENT_QUOTES) ?>">Konfiguration · Phoenix-Originalberichte</a> verwaltet. Die Synchronisierung speichert keine Zugangsdaten in Hintergrundaufgaben.</p>
    <div class="d-flex flex-wrap gap-2">
      <form method="post"><input type="hidden" name="action" value="phoenix_sync"><button class="btn btn-primary" type="submit"><i class="fa-solid fa-mobile-screen-button me-1" aria-hidden="true"></i>Phoenix-Geräte synchronisieren</button></form>
      <form method="post"><input type="hidden" name="action" value="phoenix_report_sync"><button class="btn btn-secondary" type="submit"><i class="fa-solid fa-file-pdf me-1" aria-hidden="true"></i>Phoenix-Berichte synchronisieren</button></form>
    </div>
    <p class="small text-body-secondary mt-2 mb-0">Geräte-Sync übernimmt nur lokal noch nicht vorhandene Gerätenummern. Berichts-Sync ergänzt fehlende Original-PDFs und nutzt Phoenix als zusätzliche Quellwahrheit: fehlende Importwerte werden ergänzt, widersprüchliche Werte nur dokumentiert – manuelle Prüfungen und vorhandene Werte werden nicht überschrieben.</p>
    </details>
    <?php if (current_user_is_superadmin()): ?><div class="card border-warning mb-3" id="report-regeneration" data-action-nav="Berichte neu erzeugen" data-action-icon="fa-file-pdf"><div class="card-body py-3 d-flex justify-content-between align-items-center gap-3 flex-wrap"><div><strong><i class="fa-solid fa-file-pdf me-1" aria-hidden="true"></i>Neue Prüfberichte</strong><div class="small text-body-secondary">Erzeugt die PDFs aller abgeschlossenen Importprüfungen ab 2025 erneut über den Prüfapp-Cron. Legacy-PDFs von 2024 und älter bleiben unverändert.</div></div><form method="post" class="mb-0"><input type="hidden" name="action" value="regenerate_new_reports"><button class="btn btn-warning" type="submit"><i class="fa-solid fa-rotate me-1" aria-hidden="true"></i>Alle neuen Berichte neu erzeugen</button></form></div></div><div class="card border-info mb-3" id="examiner-attribution" data-action-nav="Prüferzuordnung" data-action-icon="fa-user-pen"><div class="card-body py-3 d-flex justify-content-between align-items-center gap-3 flex-wrap"><div><strong><i class="fa-solid fa-user-pen me-1" aria-hidden="true"></i>Prüferzuordnung korrigieren</strong><div class="small text-body-secondary">Alle importierten Prüfungen: 2023/2024 werden Bea, ab 2025 Eandro zugeordnet. Die Regel gilt unabhängig vom bisherigen Prüferwert. Die Korrektur läuft als nicht abbrechbare Hintergrund-Migration.</div><?php if (is_array($examinerMigrationStats)): ?><div class="small text-success mt-1"><i class="fa-solid fa-check me-1" aria-hidden="true"></i><?= (int) $examinerMigrationStats['total'] ?> Zuordnung(en) gespeichert.</div><?php endif; ?></div><form method="post" class="mb-0" onsubmit="return confirm('Prüferzuordnung für alle importierten Prüfungen jetzt als Hintergrund-Migration starten?');"><input type="hidden" name="action" value="migrate_examiner_attribution"><button class="btn btn-info" type="submit"><i class="fa-solid fa-arrows-rotate me-1" aria-hidden="true"></i>Zuordnung starten</button></form></div></div><?php endif; ?>
    <?php if (is_array($stats) && !empty($stats['new_devices'])): ?><details class="mt-3"><summary>Neu angelegte Geräte (<?= count($stats['new_devices']) ?>)</summary><ul class="mt-2"><?php foreach ($stats['new_devices'] as $newDevice): ?><li><a href="<?= htmlspecialchars(url_for('geraete?device_id=' . (int) $newDevice['id']), ENT_QUOTES) ?>"><?= htmlspecialchars((string) $newDevice['number']) ?> · <?= htmlspecialchars((string) $newDevice['name']) ?></a></li><?php endforeach; ?></ul></details><?php endif; ?>
    <?php if (is_array($stats) && !empty($stats['updated_devices'])): ?><details class="mt-3"><summary>Aktualisierte Geräte (<?= count($stats['updated_devices']) ?>)</summary><ul class="mt-2"><?php foreach ($stats['updated_devices'] as $updatedDevice): ?><li><a href="<?= htmlspecialchars(url_for('geraete?device_id=' . (int) $updatedDevice['id']), ENT_QUOTES) ?>"><?= htmlspecialchars((string) $updatedDevice['number']) ?> · <?= htmlspecialchars((string) $updatedDevice['name']) ?></a></li><?php endforeach; ?></ul></details><?php endif; ?>
    <?php if (is_array($stats) && !empty($stats['not_imported'])): ?><details class="mt-3"><summary>Nicht importiert (<?= count($stats['not_imported']) ?>)</summary><div class="table-responsive mt-2"><table class="table table-sm"><thead><tr><th>Speicherplatz</th><th>Quelle</th><th>Grund</th></tr></thead><tbody><?php foreach ($stats['not_imported'] as $entry): ?><tr><td><?= htmlspecialchars((string) ($entry['storage_slot'] ?? '')) ?></td><td><?= htmlspecialchars((string) ($entry['source'] ?? '')) ?></td><td><?= htmlspecialchars((string) ($entry['reason'] ?? '')) ?></td></tr><?php endforeach; ?></tbody></table></div></details><?php endif; ?>
  </div>
</div>
</div>
<script>window.setNextAudit=function(days){document.getElementById('default_next_due_offset_days').value=days;};window.addImportRule=function(){const first=document.querySelector('.import-rule');const clone=first.cloneNode(true);clone.querySelectorAll('input').forEach(i=>i.value='');clone.querySelectorAll('select').forEach(s=>s.selectedIndex=0);document.getElementById('import-rules').appendChild(clone);};document.querySelectorAll('form[enctype="multipart/form-data"]').forEach(f=>f.addEventListener('submit',function(){const target=f.querySelector('#import_rules');if(!target)return;const rules=[];f.querySelectorAll('.import-rule').forEach(r=>rules.push({room:r.querySelector('.rule-room').value,device:r.querySelector('.rule-device').value,number:r.querySelector('.rule-number').value,inspection_type:r.querySelector('.rule-type').value,examiner:r.querySelector('.rule-examiner').value,next_due_offset_days:r.querySelector('.rule-days').value}));target.value=JSON.stringify(rules); }));</script>
<script>document.querySelectorAll('[data-import-date]').forEach(function(link){link.addEventListener('click',function(event){event.preventDefault();const field=document.querySelector('[name="default_test_date"]');const details=document.getElementById('pair-upload-panel');if(details)details.open=true;if(field)field.value=link.dataset.importDate;requestAnimationFrame(function(){document.getElementById('pair-upload')?.scrollIntoView({behavior:'smooth',block:'center'});if(field)field.focus({preventScroll:true});});});});</script>
<script>document.querySelectorAll('summary').forEach(function(summary){summary.childNodes.forEach(function(node){if(node.nodeType!==3)return;node.nodeValue=node.nodeValue.replace(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:[+-]\d{2}:?\d{2}|Z)/g,function(value){const date=new Date(value);return isNaN(date)?value:new Intl.DateTimeFormat('de-DE',{dateStyle:'short',timeStyle:'short'}).format(date);});});});</script>
<script>document.addEventListener('DOMContentLoaded',function(){const field=document.querySelector('form input[name="measurement_date"]');if(field&&field.type==='date'){field.required=false;field.closest('.col-md-4')?.style.setProperty('display','none');}});</script>
<script>document.addEventListener('DOMContentLoaded',function(){const form=document.querySelector('form[name="directory-import"], form[action=""]');const directory=document.getElementById('directory');const reports=document.getElementById('reports_directory');if(!directory||!reports)return;try{if(!directory.value)directory.value=localStorage.getItem('pruefapp-import-directory')||'';if(!reports.value)reports.value=localStorage.getItem('pruefapp-reports-directory')||'';}catch(_){}const save=()=>{try{localStorage.setItem('pruefapp-import-directory',directory.value);localStorage.setItem('pruefapp-reports-directory',reports.value);}catch(_){}};directory.form?.addEventListener('submit',save);reports.form?.addEventListener('submit',save);});</script>
<script>
(() => {
  const key = 'pruefapp-import-auto-refresh';
  const panel = () => document.getElementById('inspection-import-panel');
  const saveDetails = () => { const current = panel(); if (!current) return; try { sessionStorage.setItem('pruefapp-import-open-details', JSON.stringify([...current.querySelectorAll('details')].map((node, index) => node.open ? index : -1).filter(index => index >= 0))); } catch (_) {} };
  const restoreDetails = () => { const current = panel(); if (!current) return; try { const open = JSON.parse(sessionStorage.getItem('pruefapp-import-open-details') || '[]'); current.querySelectorAll('details').forEach((node, index) => { const summary = node.querySelector(':scope > summary'); const alwaysCollapsed = node.id === 'measurement-import' || summary?.textContent.trim().startsWith('Nachbearbeitung aus Import'); node.open = !alwaysCollapsed && open.includes(index); }); } catch (_) {} };
  const configure = () => {
    const current = panel(); const toggle = document.getElementById('import-auto-refresh');
    if (!current || !toggle) return;
    let enabled = false; try { enabled = localStorage.getItem(key) === '1'; } catch (_) {}
    toggle.checked = enabled;
    if (!enabled || !window.htmx) return;
    current.setAttribute('hx-get', window.location.href);
    current.setAttribute('hx-trigger', 'every 10s');
    current.setAttribute('hx-target', '#inspection-import-panel');
    current.setAttribute('hx-select', '#inspection-import-panel');
    current.setAttribute('hx-swap', 'outerHTML');
    window.htmx.process(current);
  };
  if (!window.pruefappImportAutoRefreshBound) {
    window.pruefappImportAutoRefreshBound = true;
    document.addEventListener('change', event => {
      if (event.target?.id !== 'import-auto-refresh') return;
      try { localStorage.setItem(key, event.target.checked ? '1' : '0'); } catch (_) {}
      configure();
    });
    document.body.addEventListener('htmx:beforeRequest', saveDetails);
    document.body.addEventListener('htmx:afterSwap', event => {
      if (event.target?.id !== 'inspection-import-panel') return;
      restoreDetails(); configure();
    });
  }
  restoreDetails(); configure();
})();
</script>
<script>
(() => {
  const panel = document.getElementById('import-job-refresh');
  if (!panel || panel.dataset.running !== '1') return;
  const url = panel.dataset.statusUrl; let remaining = 10; let timer = null;
  const countdown = panel.querySelector('.refresh-countdown');
  const message = panel.querySelector('.job-message'); const progress = panel.querySelector('.job-progress');
  const schedule = () => { remaining = 10; if (countdown) countdown.textContent = String(remaining); clearInterval(timer); timer = setInterval(() => { remaining--; if (countdown) countdown.textContent = String(Math.max(0, remaining)); if (remaining <= 0) { clearInterval(timer); refresh(); } }, 1000); };
  const refreshPanel = () => {
    if (!window.htmx) { window.location.reload(); return; }
    window.htmx.ajax('GET', window.location.href, {target: '#inspection-import-panel', select: '#inspection-import-panel', swap: 'outerHTML'});
  };
  const refresh = () => { if (message) message.textContent = 'Aktualisiere …'; window.ceneosAutoRefreshToast?.show(); fetch(url, {credentials: 'same-origin'}).then(response => response.json()).then(job => { if (progress) progress.textContent = job.total ? (job.step || 0) + ' / ' + job.total : '—'; if (message) message.textContent = job.message || job.error || ''; if (['done', 'error', 'cancelled'].includes(job.state)) { window.setTimeout(refreshPanel, 700); return; } schedule(); }).catch(() => { if (message) message.textContent = 'Aktualisierung fehlgeschlagen – erneuter Versuch folgt.'; schedule(); }).finally(() => window.ceneosAutoRefreshToast?.hide()); };
  schedule();
})();
</script>
<script>document.querySelectorAll('[data-phoenix-job]').forEach(function(row){const id=row.dataset.phoenixJob;const state=row.querySelector('.job-state')?.textContent.trim();if(!id||!['done','error','cancelled'].includes(state))return;const cell=row.lastElementChild;if(!cell||cell.querySelector('[data-archive-job]'))return;const form=document.createElement('form');form.method='post';form.action='<?= htmlspecialchars(url_for('admin/pruefungen/import/'), ENT_QUOTES) ?>'+id+'/archivieren';form.className='mt-1';const button=document.createElement('button');button.type='submit';button.className='btn btn-sm btn-outline-secondary';button.dataset.archiveJob='1';button.textContent='Archivieren';button.addEventListener('click',function(event){if(button.dataset.confirmed!=='1'){event.preventDefault();button.dataset.confirmed='1';button.classList.remove('btn-outline-secondary');button.classList.add('btn-outline-danger');button.textContent='Wirklich archivieren?';}});form.appendChild(button);cell.appendChild(form);const details=row.querySelector('.job-details')?.parentElement;if(details&&!details.querySelector('[data-import-link]')){const link=document.createElement('a');link.href='<?= htmlspecialchars(url_for('admin/pruefungen/import?phoenix_job='), ENT_QUOTES) ?>'+encodeURIComponent(id);link.textContent='Import anzeigen';link.className='btn btn-sm btn-link p-0';link.dataset.importLink='1';details.appendChild(link);}});</script>
<script>(() => { const button = document.getElementById('candidate-toggle-all'); if (!button) return; const details = () => [...document.querySelectorAll('#import-rebuild details.border.rounded')]; const update = () => { const allOpen = details().length > 0 && details().every(node => node.open); button.setAttribute('aria-expanded', String(allOpen)); button.innerHTML = '<i class="fa-solid ' + (allOpen ? 'fa-angles-up' : 'fa-angles-down') + ' me-1" aria-hidden="true"></i>' + (allOpen ? 'Alle einklappen' : 'Alle aufklappen'); }; button.addEventListener('click', () => { const shouldOpen = !details().every(node => node.open); details().forEach(node => { node.open = shouldOpen; }); update(); }); details().forEach(node => node.addEventListener('toggle', update)); update(); })();</script>
