<div class="card"><div class="card-body">
<h1 class="h4">Neue Prüfung</h1>
<p class="text-body-secondary">Gerät: <strong><?= htmlspecialchars((string) $device->external_number) ?> · <?= htmlspecialchars((string) $device->name) ?></strong></p>
<?php if (!empty($error)): ?><div class="alert alert-danger"><?= htmlspecialchars((string) $error) ?></div><?php endif; ?>
<form method="post" class="row g-3">
<div class="col-md-3"><label class="form-label">Prüfdatum</label><input class="form-control" type="date" name="test_date" value="<?= htmlspecialchars((string) $inspection->test_date) ?>" required><div class="form-text">Vorausgefüllt, bei Bedarf änderbar.</div></div>
<div class="col-md-9"><label class="form-label">Schutzklasse bestimmen</label><div class="row g-2" role="radiogroup"><?php foreach ([['I','Klasse I','Schuko mit Schutzleiter','fa-plug-circle-check'],['II','Klasse II','Euro-/Konturenstecker, schutzisoliert','fa-shield-halved'],['III','Klasse III','Kleinspannung ohne Netzanschluss','fa-battery-half'],['Kabel','Kabel','Kaltgeräte-/Verlängerungskabel','fa-link']] as [$class, $title, $hint, $icon]): ?><div class="col-6 col-xl-3"><label class="border rounded p-2 d-block h-100 protection-choice"><input class="visually-hidden" type="radio" name="protection_class" value="<?= $class ?>"<?= (string) $inspection->protection_class === $class ? ' checked' : '' ?>><i class="fa-solid <?= $icon ?> fs-3 d-block mb-1" aria-hidden="true"></i><strong><?= $title ?></strong><span class="d-block small text-body-secondary"><?= $hint ?></span></label></div><?php endforeach; ?></div><div class="form-text">Schutzleiterkontakt vorhanden = I; schutzisoliert = II; Kleinspannung = III.</div></div>
<div class="col-md-6"><label class="form-label">Prüfart</label><select class="form-select" name="inspection_type" required><option value="">Bitte auswählen</option><?php foreach (['I' => 'Schutzklasse I · Sicht-, Funktions- und Messprüfung', 'II' => 'Schutzklasse II · Sicht-, Funktions- und Messprüfung', 'III' => 'Schutzklasse III · Sicht- und Funktionsprüfung', 'Kabel' => 'Kabelprüfung'] as $class => $type): ?><option value="<?= htmlspecialchars($type, ENT_QUOTES) ?>"<?= (string) $inspection->inspection_type === $type ? ' selected' : '' ?>><?= htmlspecialchars($type) ?></option><?php endforeach; ?></select><div class="form-text">Durchführung durch eine prüfende Person unter Aufsicht der verantwortlichen Elektrofachkraft.</div></div>
<div class="col-md-6"><label class="form-label">Prüfer</label><?php if ($canChooseOtherExaminer): ?><select class="form-select" name="examiner" required><option value="">Bitte wählen</option><?php foreach ($users as $user): $label=trim((string) ($user->name ?? '')) . (trim((string) ($user->email ?? '')) !== '' ? ' · ' . $user->email : ''); $value=trim((string) ($user->email ?? $user->name ?? '')); ?><option value="<?= htmlspecialchars($value, ENT_QUOTES) ?>"<?= (string) $inspection->examiner === $value ? ' selected' : '' ?>><?= htmlspecialchars($label) ?></option><?php endforeach; ?></select><?php else: ?><input class="form-control" value="<?= htmlspecialchars((string) $inspection->examiner) ?>" readonly><input type="hidden" name="examiner" value="<?= htmlspecialchars((string) $inspection->examiner, ENT_QUOTES) ?>"><?php endif; ?></div>
<div class="col-md-3"><label class="form-label">Speicherplatz</label><input class="form-control" name="storage_slot" value="<?= htmlspecialchars((string) $inspection->storage_slot) ?>" placeholder="wird nach Messung eingetragen"></div>
<div class="col-md-3"><label class="form-label">Wartungsintervall</label><select class="form-select" id="interval_days" name="interval_days"><option value="182">Halbjährlich</option><option value="365" selected>Jährlich</option><option value="730">Alle zwei Jahre</option></select></div><div class="col-md-3"><label class="form-label">Nächste Prüfung</label><input class="form-control" type="date" id="next_due_date" name="next_due_date" value="<?= htmlspecialchars((string) $inspection->next_due_date) ?>"></div>
<div class="col-12"><h2 class="h6">Sichtprüfung und Funktionsprüfung</h2><?php foreach (['label' => 'Beschriftung vollständig und lesbar', 'leitung' => 'Anschlussleitung und Zugentlastung ohne erkennbare Schäden', 'gehaeuse' => 'Gehäuse und Lüftungsöffnungen ohne erkennbare Schäden', 'stecker' => 'Stecker und Kontakte unbeschädigt', 'funktion' => 'Sicherheitsrelevante Funktionen arbeiten ordnungsgemäß'] as $key => $label): ?><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="checklist[<?= $key ?>]" value="ok"<?= (($inspection->checklist_json ?? '') !== '' && str_contains((string) $inspection->checklist_json, '"' . $key . '":"ok"')) ? ' checked' : '' ?>><label class="form-check-label"><?= htmlspecialchars($label) ?></label></div><?php endforeach; ?></div>
<div class="col-md-3"><label class="form-label">Regiezeit (Minuten)</label><input class="form-control" type="number" min="0" name="regie_minutes" value="<?= (int) ($inspection->regie_minutes ?? 0) ?>"></div>
<div class="col-md-9"><label class="form-label">Begründung Regiezeit</label><input class="form-control" name="regie_reason" value="<?= htmlspecialchars((string) ($inspection->regie_reason ?? '')) ?>"></div>
<div class="col-12 d-flex gap-2"><button class="btn btn-outline-primary" name="complete" value="0">Zwischenspeichern</button><button class="btn btn-primary" name="complete" value="1">Prüfung abschließen</button></div>
</form></div></div>
<script>
(() => {
  const date = document.querySelector('[name="test_date"]');
  const interval = document.getElementById('interval_days');
  const next = document.getElementById('next_due_date');
  if (!date || !interval || !next) return;
  const update = () => { if (!date.value) return; const d = new Date(date.value + 'T12:00:00'); d.setDate(d.getDate() + Number(interval.value || 365)); next.value = d.toISOString().slice(0, 10); };
  interval.addEventListener('change', update); date.addEventListener('change', update);
})();
</script>
