<style>#settings-ai-panel .form-control,#settings-ai-panel .form-select,#settings-ai-panel .ts-control{min-height:2.75rem}#settings-ai-panel summary{cursor:pointer}</style>
<section class="card shadow-sm" id="settings-ai-panel" data-action-nav="KI-Stammdatenprüfung" data-action-icon="fa-wand-magic-sparkles">
  <div class="card-header d-flex flex-wrap align-items-center justify-content-between gap-2"><strong><i class="fa-solid fa-wand-magic-sparkles me-1" aria-hidden="true"></i>KI &amp; Stammdatenprüfung</strong><div class="d-flex gap-2"><label class="form-check form-switch mb-0"><input class="form-check-input" type="checkbox" form="ai-provider-form" name="vocabulary_ai_enabled" value="1"<?= !empty($enabled) ? ' checked' : '' ?>><span class="form-check-label small">Prüfung aktiv</span></label></div></div>
  <div class="card-body">
    <p class="small text-body-secondary">Ein Provider kann später auch für weitere KI-Aufgaben genutzt werden. Die Stammdatenprüfung übermittelt nur kurze Hersteller-, Modell- und Bezeichnungswerte und erzeugt ausschließlich Freigabevorschläge.</p>
    <?php if ($message !== ''): ?><div class="alert alert-success py-2"><i class="fa-solid fa-circle-check me-1" aria-hidden="true"></i><?= htmlspecialchars($message, ENT_QUOTES) ?></div><?php endif; ?>
    <?php if ($error !== ''): ?><div class="alert alert-danger py-2"><i class="fa-solid fa-triangle-exclamation me-1" aria-hidden="true"></i><?= htmlspecialchars($error, ENT_QUOTES) ?></div><?php endif; ?>
    <div class="d-flex flex-wrap align-items-end gap-2 mb-3"><div class="flex-grow-1"><label class="form-label mb-1" for="ai-provider-choice">Provider</label><select class="form-select" id="ai-provider-choice" hx-get="<?= htmlspecialchars(url_for('admin/konfiguration/ki-provider'), ENT_QUOTES) ?>" hx-target="#settings-ai-panel" hx-swap="outerHTML" hx-trigger="change" name="provider_id"><option value="0">Neuen Provider anlegen</option><?php foreach ($providers as $item): ?><option value="<?= (int) $item->id ?>"<?= (int) $provider->id === (int) $item->id ? ' selected' : '' ?>><?= htmlspecialchars((string) $item->name, ENT_QUOTES) ?></option><?php endforeach; ?></select></div><div><label class="form-label mb-1" for="ai-provider-preset">Voreinstellung</label><select class="form-select" id="ai-provider-preset" data-ai-provider-preset><option value="">Keine auswählen</option><option value="innogpt">innoGPT</option><option value="ionos">IONOS AI Model Hub</option><option value="ovh">OVHcloud AI Endpoints</option></select></div><button class="btn btn-outline-secondary" type="button" hx-get="<?= htmlspecialchars(url_for('admin/konfiguration/ki-provider?provider_id=0'), ENT_QUOTES) ?>" hx-target="#settings-ai-panel" hx-swap="outerHTML"><i class="fa-solid fa-plus me-1" aria-hidden="true"></i>Provider hinzufügen</button></div>
    <form id="ai-provider-form" method="post" action="<?= htmlspecialchars(url_for('admin/konfiguration/ki-provider'), ENT_QUOTES) ?>" hx-post="<?= htmlspecialchars(url_for('admin/konfiguration/ki-provider'), ENT_QUOTES) ?>" hx-target="#settings-ai-panel" hx-swap="outerHTML" class="row g-3 ai-provider-form">
      <input type="hidden" name="provider_id" value="<?= (int) $provider->id ?>">
      <div class="col-md-4"><label class="form-label" for="ai-provider-name">Name</label><input class="form-control" id="ai-provider-name" name="name" value="<?= htmlspecialchars((string) $provider->name, ENT_QUOTES) ?>" placeholder="z. B. innoGPT"></div>
      <div class="col-md-5"><label class="form-label" for="ai-provider-url">OpenAI-kompatible Basis-URL</label><input class="form-control" type="url" id="ai-provider-url" name="base_url" value="<?= htmlspecialchars((string) $provider->base_url, ENT_QUOTES) ?>" placeholder="https://anbieter.example/v1" required></div>
      <div class="col-md-3"><label class="form-label" for="ai-provider-header">Token-Header</label><select class="form-select" id="ai-provider-header" name="header_name"><option value="Authorization"<?= (string) $provider->header_name === 'Authorization' ? ' selected' : '' ?>>Authorization: Bearer</option><option value="X-API-Key"<?= (string) $provider->header_name === 'X-API-Key' ? ' selected' : '' ?>>X-API-Key</option></select></div>
      <div class="col-md-6"><label class="form-label" for="ai-provider-token">API-Token<?= (string) $provider->api_token !== '' ? ' (gesetzt)' : '' ?></label><input class="form-control" type="password" id="ai-provider-token" name="api_token" autocomplete="new-password" placeholder="<?= (string) $provider->api_token !== '' ? 'Unverändert lassen' : 'Token eingeben' ?>"></div>
      <div class="col-md-6"><label class="form-label" for="ai-provider-pricing">Eigener Preis-/Dokumentationslink</label><input class="form-control" type="url" id="ai-provider-pricing" name="pricing_url" value="<?= htmlspecialchars((string) $provider->pricing_url, ENT_QUOTES) ?>" placeholder="optional; erkannte Provider sind automatisch verlinkt"></div>
      <div class="col-12"><label class="form-label" for="ai-provider-model">Modell für die Stammdatenprüfung</label><select class="form-select" id="ai-provider-model" name="vocabulary_ai_model" data-search-select><option value="">Nach Verbindungstest auswählen</option><?php foreach ($models as $model): ?><option value="<?= htmlspecialchars($model, ENT_QUOTES) ?>"<?= $selectedModel === $model ? ' selected' : '' ?>><?= htmlspecialchars($model, ENT_QUOTES) ?></option><?php endforeach; ?></select><div class="form-text">Das Modell wird nur für Vorschläge zu Hersteller, Modell und Gerätebezeichnung verwendet.</div></div>
      <div class="col-12 d-flex flex-wrap gap-2"><button class="btn btn-secondary" type="submit" name="action" value="test"><i class="fa-solid fa-plug me-1" aria-hidden="true"></i>Verbindung testen &amp; Modelle laden</button><button class="btn btn-primary" type="submit" name="action" value="save"><i class="fa-solid fa-floppy-disk me-1" aria-hidden="true"></i>Für Stammdatenprüfung speichern</button><?php if (($pricingUrl ?? '') !== ''): ?><a class="btn btn-outline-secondary" href="<?= htmlspecialchars((string) $pricingUrl, ENT_QUOTES) ?>" target="_blank" rel="noopener"><i class="fa-solid fa-arrow-up-right-from-square me-1" aria-hidden="true"></i>Preise &amp; Nutzung von <?= htmlspecialchars((string) $provider->name, ENT_QUOTES) ?></a><?php endif; ?></div>
      <div class="col-12"><details<?= (string) $provider->auth_mode === 'oauth' ? ' open' : '' ?>><summary class="small fw-semibold"><i class="fa-solid fa-key me-1" aria-hidden="true"></i>OAuth 2.0 statt API-Token verwenden</summary><div class="row g-3 mt-1"><div class="col-md-3"><label class="form-label" for="ai-provider-auth-mode">Anmeldung</label><select class="form-select" id="ai-provider-auth-mode" name="auth_mode"><option value="token"<?= (string) $provider->auth_mode !== 'oauth' ? ' selected' : '' ?>>Token / API-Key</option><option value="oauth"<?= (string) $provider->auth_mode === 'oauth' ? ' selected' : '' ?>>OAuth 2.0 mit PKCE</option></select></div><div class="col-md-5"><label class="form-label" for="ai-oauth-authorize">Autorisierungs-URL</label><input class="form-control" type="url" id="ai-oauth-authorize" name="oauth_authorization_url" value="<?= htmlspecialchars((string) $provider->oauth_authorization_url, ENT_QUOTES) ?>"></div><div class="col-md-4"><label class="form-label" for="ai-oauth-token">Token-URL</label><input class="form-control" type="url" id="ai-oauth-token" name="oauth_token_url" value="<?= htmlspecialchars((string) $provider->oauth_token_url, ENT_QUOTES) ?>"></div><div class="col-md-4"><label class="form-label" for="ai-oauth-client">Client-ID</label><input class="form-control" id="ai-oauth-client" name="oauth_client_id" value="<?= htmlspecialchars((string) $provider->oauth_client_id, ENT_QUOTES) ?>"></div><div class="col-md-4"><label class="form-label" for="ai-oauth-secret">Client-Secret</label><input class="form-control" type="password" id="ai-oauth-secret" name="oauth_client_secret" autocomplete="new-password" placeholder="optional / unverändert lassen"></div><div class="col-md-4"><label class="form-label" for="ai-oauth-scopes">Scopes</label><input class="form-control" id="ai-oauth-scopes" name="oauth_scopes" value="<?= htmlspecialchars((string) $provider->oauth_scopes, ENT_QUOTES) ?>"></div></div><div class="d-flex flex-wrap align-items-center gap-2 mt-3"><button class="btn btn-outline-success" type="submit" name="action" value="oauth"><i class="fa-solid fa-right-to-bracket me-1" aria-hidden="true"></i>OAuth verbinden</button><span class="small text-body-secondary"><?= (string) $provider->oauth_access_token !== '' ? 'OAuth verbunden; Token wird automatisch erneuert.' : 'Callback: ' . VocabularyOAuthService::callbackUrl() ?></span></div></details></div>
    </form>
  </div>
</section>
<script>
(() => {
  const panel = document.getElementById('settings-ai-panel');
  const select = panel?.querySelector('[data-ai-provider-preset]');
  if (!panel || !select || select.dataset.bound === '1') return;
  select.dataset.bound = '1';
  const presets = {
    innogpt: {name: 'innoGPT', base_url: 'https://app.innogpt.de/api/ext/v1', header_name: 'Authorization', pricing_url: 'https://docs.innogpt.de/en/help/articles/8468742-usage-limits-andamp-fair-use-policy'},
    ionos: {name: 'IONOS AI Model Hub', base_url: 'https://openai.inference.de-txl.ionos.com/v1', header_name: 'Authorization', pricing_url: 'https://docs.ionos.com/cloud/ai/ai-model-hub/ai-model-hub'},
    ovh: {name: 'OVHcloud AI Endpoints', base_url: 'https://oai.endpoints.kepler.ai.cloud.ovh.net/v1', header_name: 'Authorization', pricing_url: 'https://help.ovhcloud.com/csm/en-au-public-cloud-ai-endpoints-code-assistant?id=kb_article_view&sysparm_article=KB0067282'}
  };
  select.addEventListener('change', () => {
    const preset = presets[select.value];
    if (!preset) return;
    Object.entries(preset).forEach(([name, value]) => {
      const field = panel.querySelector(`[name="${name}"]`);
      if (field) field.value = value;
    });
    panel.querySelector('[name="api_token"]')?.focus();
  });
})();
</script>
