<style>#settings-ai-panel .form-control,#settings-ai-panel .form-select,#settings-ai-panel .ts-control{min-height:2.75rem}#settings-ai-panel summary{cursor:pointer}</style>
<section class="card shadow-sm" id="settings-ai-panel" data-action-nav="KI-Stammdatenprüfung" data-action-icon="fa-wand-magic-sparkles">
  <div class="card-header"><strong><i class="fa-solid fa-wand-magic-sparkles me-1" aria-hidden="true"></i>KI &amp; Stammdatenprüfung</strong></div>
  <div class="card-body">
    <p class="small text-body-secondary">Ein Provider kann später auch für weitere KI-Aufgaben genutzt werden. Die Stammdatenprüfung übermittelt nur kurze Hersteller-, Modell- und Bezeichnungswerte und erzeugt ausschließlich Freigabevorschläge.</p>
    <?php if ($message !== ''): ?><div class="alert alert-success py-2"><i class="fa-solid fa-circle-check me-1" aria-hidden="true"></i><?= htmlspecialchars($message, ENT_QUOTES) ?></div><?php endif; ?>
    <?php if ($error !== ''): ?><div class="alert alert-danger py-2"><i class="fa-solid fa-triangle-exclamation me-1" aria-hidden="true"></i><?= htmlspecialchars($error, ENT_QUOTES) ?></div><?php endif; ?>
    <?php if (is_array($diagnostic ?? null)): ?><div class="alert alert-info py-2"><i class="fa-solid fa-stethoscope me-1" aria-hidden="true"></i><strong>KI-Testdiagnose:</strong> Antwortmodell <?= htmlspecialchars((string) $diagnostic['model'], ENT_QUOTES) ?><?= (string) $diagnostic['content'] !== '' ? ' · Antwort: ' . htmlspecialchars((string) $diagnostic['content'], ENT_QUOTES) : '' ?>.</div><?php endif; ?>
    <div class="d-flex flex-wrap align-items-end gap-2 mb-3"><div class="flex-grow-1"><label class="form-label mb-1" for="ai-provider-choice">Provider</label><select class="form-select" id="ai-provider-choice" hx-get="<?= htmlspecialchars(url_for('admin/konfiguration/ki-provider'), ENT_QUOTES) ?>" hx-target="#settings-ai-panel" hx-swap="outerHTML" hx-trigger="change" name="provider_id" data-no-search><option value="0">Neuen Provider anlegen</option><?php foreach ($providers as $item): ?><option value="<?= (int) $item->id ?>"<?= (int) $provider->id === (int) $item->id ? ' selected' : '' ?>><?= htmlspecialchars((string) $item->name, ENT_QUOTES) ?></option><?php endforeach; ?></select></div><div><label class="form-label mb-1" for="ai-provider-preset">Voreinstellung</label><select class="form-select" id="ai-provider-preset" data-ai-provider-preset data-no-search><option value="">Keine auswählen</option><option value="innogpt">innoGPT</option><option value="ionos">IONOS AI Model Hub</option><option value="ovh">OVHcloud AI Endpoints</option></select></div><button class="btn btn-outline-secondary" type="button" hx-get="<?= htmlspecialchars(url_for('admin/konfiguration/ki-provider?provider_id=0'), ENT_QUOTES) ?>" hx-target="#settings-ai-panel" hx-swap="outerHTML"><i class="fa-solid fa-plus me-1" aria-hidden="true"></i>Provider hinzufügen</button></div>
    <form id="ai-provider-form" method="post" action="<?= htmlspecialchars(url_for('admin/konfiguration/ki-provider'), ENT_QUOTES) ?>" hx-post="<?= htmlspecialchars(url_for('admin/konfiguration/ki-provider'), ENT_QUOTES) ?>" hx-target="#settings-ai-panel" hx-swap="outerHTML" class="row g-3 ai-provider-form">
      <input type="hidden" name="provider_id" value="<?= (int) $provider->id ?>">
      <div class="col-12"><section class="border rounded-3 p-3"><h2 class="h6 mb-3"><i class="fa-solid fa-plug me-1 text-body-secondary" aria-hidden="true"></i>Provider-Zugang</h2><div class="row g-3">
      <div class="col-md-4"><label class="form-label" for="ai-provider-name">Name</label><input class="form-control" id="ai-provider-name" name="name" value="<?= htmlspecialchars((string) $provider->name, ENT_QUOTES) ?>" placeholder="z. B. innoGPT"></div>
      <div class="col-md-5"><label class="form-label" for="ai-provider-url">OpenAI-kompatible Basis-URL</label><input class="form-control" type="url" id="ai-provider-url" name="base_url" value="<?= htmlspecialchars((string) $provider->base_url, ENT_QUOTES) ?>" placeholder="https://anbieter.example/v1" required></div>
      <div class="col-md-3"><label class="form-label" for="ai-provider-header">Token-Header</label><select class="form-select" id="ai-provider-header" name="header_name" data-no-search><option value="Authorization"<?= (string) $provider->header_name === 'Authorization' ? ' selected' : '' ?>>Authorization: Bearer</option><option value="X-API-Key"<?= (string) $provider->header_name === 'X-API-Key' ? ' selected' : '' ?>>X-API-Key</option></select></div>
      <div class="col-md-6"><label class="form-label" for="ai-provider-token">API-Token<?= (string) $provider->api_token !== '' ? ' (gesetzt)' : '' ?></label><input class="form-control" type="password" id="ai-provider-token" name="api_token" autocomplete="new-password" placeholder="<?= (string) $provider->api_token !== '' ? 'Unverändert lassen' : 'Token eingeben' ?>"></div>
      <div class="col-md-6"><label class="form-label" for="ai-provider-pricing">Eigener Preis-/Dokumentationslink</label><input class="form-control" type="url" id="ai-provider-pricing" name="pricing_url" value="<?= htmlspecialchars((string) $provider->pricing_url, ENT_QUOTES) ?>" placeholder="optional; erkannte Provider sind automatisch verlinkt"></div>
      <div class="col-12 d-flex flex-wrap gap-2"><button class="btn btn-secondary" type="submit" name="action" value="test"><i class="fa-solid fa-plug me-1" aria-hidden="true"></i>Verbindung testen &amp; Modelle laden</button><button class="btn btn-outline-primary" type="submit" name="action" value="save_provider"><i class="fa-solid fa-floppy-disk me-1" aria-hidden="true"></i>Provider speichern</button><?php if (($pricingUrl ?? '') !== ''): ?><a class="btn btn-outline-secondary" href="<?= htmlspecialchars((string) $pricingUrl, ENT_QUOTES) ?>" target="_blank" rel="noopener"><i class="fa-solid fa-arrow-up-right-from-square me-1" aria-hidden="true"></i>Preise &amp; Nutzung von <?= htmlspecialchars((string) $provider->name, ENT_QUOTES) ?></a><?php endif; ?></div>
      </div></section></div>
      <?php
      $providerIdentifier = mb_strtolower((string) $provider->name . ' ' . (string) $provider->base_url, 'UTF-8');
      $isInnoGpt = str_contains($providerIdentifier, 'innogpt');
      $isOvh = str_contains($providerIdentifier, 'ovh');
      ?>
      <div class="col-12"><section class="border rounded-3 p-3 bg-body-tertiary"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 class="h6 mb-0"><i class="fa-solid fa-spell-check me-1 text-body-secondary" aria-hidden="true"></i>Stammdatenprüfung</h2><p class="small text-body-secondary mb-0">Dieser Provider und das gewählte Modell werden nur für Freigabevorschläge zu Hersteller, Modell und Gerätebezeichnung verwendet.</p></div><label class="form-check form-switch mb-0"><input class="form-check-input" type="checkbox" name="vocabulary_ai_enabled" value="1"<?= !empty($enabled) ? ' checked' : '' ?>><span class="form-check-label">Prüfung aktiv</span></label></div><label class="form-label" for="ai-provider-model">Modell</label><input class="form-control" id="ai-provider-model" name="vocabulary_ai_model" list="ai-provider-model-options" value="<?= htmlspecialchars($selectedModel, ENT_QUOTES) ?>" placeholder="Modell auswählen oder eingeben"><datalist id="ai-provider-model-options"><?php if ($isInnoGpt): ?><option value="smart">smart · automatische Modellauswahl</option><?php elseif ($isOvh): ?><option value="mistral@latest">mistral@latest · automatisch aktuelles Mistral-Modell</option><?php endif; ?><?php foreach ($models as $model): if (in_array($model, ['smart', 'mistral@latest'], true)) continue; ?><option value="<?= htmlspecialchars($model, ENT_QUOTES) ?>"><?php endforeach; ?></datalist><div class="form-text mb-3"><?php if ($isInnoGpt): ?>„smart“ ist die automatische Modellauswahl von innoGPT. Falls der Zugang dafür nicht freigeschaltet ist, zeigt die KI-Testanfrage den Hinweis des Anbieters; dann kann ein konkretes Modell gewählt werden.<?php elseif ($isOvh): ?>OVH Virtual Models wählen serverseitig das neueste passende Mistral-Modell; ein konkretes Modell kann jederzeit eingetragen werden.<?php else: ?>Nach dem Verbindungstest kannst du ein Modell aus der Liste wählen oder selbst eintragen.<?php endif; ?></div><div class="d-flex flex-wrap gap-2"><button class="btn btn-primary" type="submit" name="action" value="save_vocabulary"><i class="fa-solid fa-floppy-disk me-1" aria-hidden="true"></i>Stammdatenprüfung speichern</button><button class="btn btn-outline-info" type="submit" name="action" value="diagnose"><i class="fa-solid fa-stethoscope me-1" aria-hidden="true"></i>KI-Testanfrage</button></div></section></div>
      <div class="col-12"><details<?= (string) $provider->auth_mode === 'oauth' ? ' open' : '' ?>><summary class="small fw-semibold"><i class="fa-solid fa-key me-1" aria-hidden="true"></i>OAuth 2.0 statt API-Token verwenden</summary><div class="row g-3 mt-1"><div class="col-md-3"><label class="form-label" for="ai-provider-auth-mode">Anmeldung</label><select class="form-select" id="ai-provider-auth-mode" name="auth_mode" data-no-search><option value="token"<?= (string) $provider->auth_mode !== 'oauth' ? ' selected' : '' ?>>Token / API-Key</option><option value="oauth"<?= (string) $provider->auth_mode === 'oauth' ? ' selected' : '' ?>>OAuth 2.0 mit PKCE</option></select></div><div class="col-md-5"><label class="form-label" for="ai-oauth-authorize">Autorisierungs-URL</label><input class="form-control" type="url" id="ai-oauth-authorize" name="oauth_authorization_url" value="<?= htmlspecialchars((string) $provider->oauth_authorization_url, ENT_QUOTES) ?>"></div><div class="col-md-4"><label class="form-label" for="ai-oauth-token">Token-URL</label><input class="form-control" type="url" id="ai-oauth-token" name="oauth_token_url" value="<?= htmlspecialchars((string) $provider->oauth_token_url, ENT_QUOTES) ?>"></div><div class="col-md-4"><label class="form-label" for="ai-oauth-client">Client-ID</label><input class="form-control" id="ai-oauth-client" name="oauth_client_id" value="<?= htmlspecialchars((string) $provider->oauth_client_id, ENT_QUOTES) ?>"></div><div class="col-md-4"><label class="form-label" for="ai-oauth-secret">Client-Secret</label><input class="form-control" type="password" id="ai-oauth-secret" name="oauth_client_secret" autocomplete="new-password" placeholder="optional / unverändert lassen"></div><div class="col-md-4"><label class="form-label" for="ai-oauth-scopes">Scopes</label><input class="form-control" id="ai-oauth-scopes" name="oauth_scopes" value="<?= htmlspecialchars((string) $provider->oauth_scopes, ENT_QUOTES) ?>"></div></div><div class="d-flex flex-wrap align-items-center gap-2 mt-3"><button class="btn btn-outline-success" type="submit" name="action" value="oauth"><i class="fa-solid fa-right-to-bracket me-1" aria-hidden="true"></i>OAuth verbinden</button><span class="small text-body-secondary"><?= (string) $provider->oauth_access_token !== '' ? 'OAuth verbunden; Token wird automatisch erneuert.' : 'Callback: ' . VocabularyOAuthService::callbackUrl() ?></span></div></details></div>
    </form>
  </div>
</section>
<script>
(() => {
  const panel = document.getElementById('settings-ai-panel');
  const select = panel?.querySelector('[data-ai-provider-preset]');
  if (!panel || !select || select.dataset.bound === '1') return;
  select.dataset.bound = '1';
  const presets = {
    innogpt: {name: 'innoGPT', base_url: 'https://app.innogpt.de/api/ext/v1', header_name: 'Authorization', pricing_url: 'https://docs.innogpt.de/en/help/articles/8468742-usage-limits-andamp-fair-use-policy', vocabulary_ai_model: 'smart'},
    ionos: {name: 'IONOS AI Model Hub', base_url: 'https://openai.inference.de-txl.ionos.com/v1', header_name: 'Authorization', pricing_url: 'https://docs.ionos.com/cloud/ai/ai-model-hub/ai-model-hub'},
    ovh: {name: 'OVHcloud AI Endpoints', base_url: 'https://oai.endpoints.kepler.ai.cloud.ovh.net/v1', header_name: 'Authorization', pricing_url: 'https://help.ovhcloud.com/csm/en-au-public-cloud-ai-endpoints-code-assistant?id=kb_article_view&sysparm_article=KB0067282', vocabulary_ai_model: 'mistral@latest'}
  };
  select.addEventListener('change', () => {
    const preset = presets[select.value];
    if (!preset) return;
    Object.entries(preset).forEach(([name, value]) => {
      const field = panel.querySelector(`[name="${name}"]`);
      if (!field) return;
      if (field.tagName === 'SELECT' && ![...field.options].some(option => option.value === value)) field.add(new Option(value === 'smart' ? 'smart · automatische Modellauswahl' : (value === 'mistral@latest' ? 'mistral@latest · automatisch aktuelles Mistral-Modell' : value), value));
      field.value = value;
    });
    panel.querySelector('[name="api_token"]')?.focus();
  });
})();
</script>
