<section class="card shadow-sm" id="vocabulary-review-panel" data-action-nav="Stammdaten bereinigen" data-action-icon="fa-spell-check">
  <div class="card-header d-flex flex-wrap justify-content-between align-items-center gap-2">
    <h1 class="h5 mb-0"><i class="fa-solid fa-spell-check me-2" aria-hidden="true"></i>Stammdaten bereinigen</h1>
    <span class="badge text-bg-primary"><?= count($reviews) ?> offen</span>
  </div>
  <div class="card-body">
    <p class="text-body-secondary">KI-Vorschläge ändern nichts automatisch. Prüfe die Zusammenführung vor dem Freigeben; Rohimportdaten und Legacy-PDFs bleiben unverändert.</p>
    <?php if (($message ?? '') !== ''): ?><div class="alert alert-success py-2"><i class="fa-solid fa-circle-check me-1" aria-hidden="true"></i><?= htmlspecialchars((string) $message, ENT_QUOTES) ?></div><?php endif; ?>
    <?php if (($error ?? '') !== ''): ?><div class="alert alert-danger py-2"><i class="fa-solid fa-triangle-exclamation me-1" aria-hidden="true"></i><?= htmlspecialchars((string) $error, ENT_QUOTES) ?></div><?php endif; ?>
    <section class="border rounded-3 p-3 mb-3 bg-body-tertiary"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2"><div><h2 class="h6 mb-1"><i class="fa-solid fa-wand-magic-sparkles me-1" aria-hidden="true"></i>Vorhandene Stammdaten prüfen</h2><p class="small text-body-secondary mb-0">Prüft nur noch nicht entschiedene Werte. Vorschläge werden niemals automatisch übernommen.</p></div><form method="post" hx-post="<?= htmlspecialchars(url_for('admin/stammdaten'), ENT_QUOTES) ?>" hx-target="#vocabulary-review-panel" hx-swap="outerHTML"><button class="btn btn-primary" name="action" value="scan"<?= empty($canSuggest) ? ' disabled' : '' ?>><i class="fa-solid fa-play me-1" aria-hidden="true"></i>Prüfung starten</button></form></div><?php if (empty($canSuggest)): ?><div class="form-text text-warning-emphasis mt-2">Provider, Modell und Aktivierung der Stammdatenprüfung müssen zuerst in der Konfiguration gespeichert werden.</div><?php endif; ?><?php if (($jobs ?? []) !== []): ?><div class="table-responsive mt-3"><table class="table table-sm mb-0"><thead><tr><th>Hintergrundaufgabe</th><th>Status</th><th>Fortschritt</th><th>Meldung</th></tr></thead><tbody><?php foreach ($jobs as $job): ?><tr><td><?= htmlspecialchars((string) ($job['label'] ?? 'KI-Stammdatenprüfung'), ENT_QUOTES) ?></td><td><?= htmlspecialchars((string) ($job['state'] ?? ''), ENT_QUOTES) ?></td><td><?= (int) ($job['current'] ?? 0) ?> von <?= (int) ($job['total'] ?? 0) ?></td><td class="small text-body-secondary"><?= htmlspecialchars((string) ($job['message'] ?? ''), ENT_QUOTES) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
    <?php if ($reviews === []): ?><div class="alert alert-success mb-0"><i class="fa-solid fa-circle-check me-1" aria-hidden="true"></i>Keine offenen Vorschläge.</div><?php endif; ?>
    <?php foreach (DeviceVocabularyService::FIELDS as $field): $rows = array_values(array_filter($reviews, static fn($review): bool => (string) $review->field_name === $field)); if ($rows === []) continue; $label = ['manufacturer' => 'Hersteller', 'device_model' => 'Modelle', 'name' => 'Gerätebezeichnungen'][$field]; ?>
      <h2 class="h6 mt-4"><i class="fa-solid fa-tag me-1" aria-hidden="true"></i><?= htmlspecialchars($label) ?></h2>
      <div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Quellwert</th><th>Vorschlag</th><th>Sicherheit</th><th>Begründung</th><th>Aktion</th></tr></thead><tbody>
      <?php foreach ($rows as $review): ?><tr><td><code><?= htmlspecialchars((string) $review->source_value) ?></code></td><td><?= htmlspecialchars((string) $review->suggested_value ?: 'Kein sicherer Vorschlag') ?></td><td><?= number_format((float) $review->confidence * 100, 0) ?> %</td><td class="small text-body-secondary"><?= htmlspecialchars((string) $review->reason) ?></td><td><form method="post" class="d-flex flex-wrap gap-1"><input type="hidden" name="review_id" value="<?= (int) $review->id ?>"><input class="form-control form-control-sm" name="canonical_value" value="<?= htmlspecialchars((string) $review->suggested_value) ?>" placeholder="Zielwert"><button class="btn btn-sm btn-primary" name="action" value="merge"><i class="fa-solid fa-code-merge me-1" aria-hidden="true"></i>Zusammenführen</button><button class="btn btn-sm btn-outline-secondary" name="action" value="keep"><i class="fa-solid fa-keep me-1" aria-hidden="true"></i>Behalten</button></form></td></tr><?php endforeach; ?>
      </tbody></table></div>
    <?php endforeach; ?>
  </div>
</section>
